### ISSUE TITLE
Question about issue 1123

### ISSUE THREAD

**Issue by Tanco-K** [CESNET/libyang#1282]
Hi!

I see that issue-1123 modified  lyxml_correct_elem_ns
code：
```C
        if (iter->content[0] && copy_ns) {
            lyxml_correct_content_ns(ctx, iter, orig);
        }
```
When trying to send RPC like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="19">
<edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <target>
    <running/>
  </target>
  <config>
    <test1 xmlns="urn:com:test">
      <abc>
        <users>
          <user>
            <userstr>******<online-num>******</online-num>
            </userstr>
          </user>
        </users>
      </abc>
    </test1>
  </config>
</edit-config>
</rpc>
```

=================
it cause coredump:
=================
```
(gdb) bt
#0  0xed2ad9d2 in lyxml_correct_elem_ns (ctx=<optimized out>, elem=<optimized out>, orig=<optimized out>, copy_ns=<optimized out>, correct_attrs=<optimized out>)
    at libyang/src/xml.c:243

#1  0xed0d878e in xml_parse_data (ctx=ctx@entry=0xeb74a138, xml=xml@entry=0xe978d168, parent=<optimized out>, first_sibling=<optimized out>, prev=<optimized out>, options=<optimized out>, unres=<optimized out>, result=<optimized out>, 
    act_notif=<optimized out>, yang_data_name=<optimized out>) at libyang/src/parser_xml.c:506

#2  0xed0d7fce in xml_parse_data (ctx=ctx@entry=0xeb74a138, xml=xml@entry=0xe97843e8, parent=parent@entry=0x0, first_sibling=<optimized out>, prev=<optimized out>, options=<optimized out>, unres=<optimized out>, 
    result=<optimized out>, act_notif=<optimized out>, yang_data_name=<optimized out>) at libyang/src/parser_xml.c:554

#3  0xed0dc3db in lyd_parse_xml (ctx=<optimized out>, root=<optimized out>, options=528) at libyang/src/parser_xml.c:732
```
=============================
it accessed null-pointer : if (iter->content[0]
```
 p *(struct lyxml_elem *)iter
$9 = {flags = 1 '\001', parent = 0xe975db28, attr = 0x0, child = 0xe975dc28, next = 0x0, prev = 0xe975dba8, name = 0xe9ab9268 "userstr", ns = 0xea7052a8, content = 0x0}
```

**Comment by michalvasko** [comment]
Okay, should be fixed.

**Comment by Tanco-K** [comment]
ok，that's good！:)
