### ISSUE TITLE
ly2: duplicate includes in submodules causes problems

### ISSUE THREAD

**Issue by choppsv1** [CESNET/libyang#1353]
This parses with libyang1, and fails with libyang2

main.yang:
```
module main {
  yang-version 1.1;
  namespace "http://example.com/main";
  prefix m;
  include common;
  include a;
}
```
common.yang:
```
submodule common {
  yang-version 1.1;
  belongs-to main { prefix m; }
}
```
a.yang
```
submodule a {
  yang-version 1.1;
  belongs-to main { prefix m; }
  include common;
}
```

```
$ yanglint main.yang
libyang err : Including "common" submodule into "main" failed.
libyang err : Including "a" submodule into "main" failed.
YANGLINT[E]: Processing schema module from main.yang failed.
```

**Comment by choppsv1** [comment]
I've edited this issue to replace earlier text with simple repro details.

**Comment by rkrejci** [comment]
Thanks for reporting and for the data to reproduce, the issue should be now fixed in libyang2 branch. Please test and confirm that it works for you.

**Comment by choppsv1** [comment]
This immediate problem is fixed; however, when I run it on the actual models from FRR that found this I get another SIGSEGV

```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
libyang warn: YANG version 1.1 expects all includes in main module, includes in submodules (frr-bgp-common-structure) are not necessary.
libyang warn: YANG version 1.1 expects all includes in main module, includes in submodules (frr-bgp-common-multiprotocol) are not necessary.
libyang warn: YANG version 1.1 expects all includes in main module, includes in submodules (frr-bgp-neighbor) are not necessary.
libyang warn: YANG version 1.1 expects all includes in main module, includes in submodules (frr-bgp-neighbor) are not necessary.
libyang warn: YANG version 1.1 expects all includes in main module, includes in submodules (frr-bgp-peer-group) are not necessary.
libyang warn: YANG version 1.1 expects all includes in main module, includes in submodules (frr-bgp-peer-group) are not necessary.
libyang warn: YANG version 1.1 expects all includes in main module, includes in submodules (frr-bgp-bmp) are not necessary.
libyang warn: Container "ipv4-unicast" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "ipv6-unicast" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "ipv4-labeled-unicast" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "ipv6-labeled-unicast" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "l3vpn-ipv4-unicast" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "l3vpn-ipv6-unicast" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "l3vpn-ipv4-multicast" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "l3vpn-ipv6-multicast" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "l2vpn-vpls" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "l2vpn-evpn" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "ipv4-multicast" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "ipv6-multicast" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "ipv4-flowspec" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "ipv6-flowspec" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "ipv4-unicast" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "ipv6-unicast" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "ipv4-labeled-unicast" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "ipv6-labeled-unicast" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "l3vpn-ipv4-unicast" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "l3vpn-ipv6-unicast" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "l3vpn-ipv4-multicast" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "l3vpn-ipv6-multicast" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "l2vpn-vpls" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "l2vpn-evpn" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "ipv4-multicast" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "ipv6-multicast" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "ipv4-flowspec" changed to presence because it has a meaning from its "when" condition.
libyang warn: Container "ipv6-flowspec" changed to presence because it has a meaning from its "when" condition.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b186a9 in lys_compile_uses_find_grouping (ctx=0x7fffffffbd70, uses_p=0x5555558032d0, grp_p=0x7fffffffb428, grp_pmod=0x7fffffffb430) at /home/chopps/w/ly2/src/schema_compile_node.c:3322
3322                    grp = pmod->includes[u].submodule->groupings;
(gdb)
#0  0x00007ffff7b186a9 in lys_compile_uses_find_grouping (ctx=0x7fffffffbd70, uses_p=0x5555558032d0, grp_p=0x7fffffffb428, grp_pmod=0x7fffffffb430) at /home/chopps/w/ly2/src/schema_compile_node.c:3322
#1  0x00007ffff7b1890e in lys_compile_uses (ctx=0x7fffffffbd70, uses_p=0x5555558032d0, parent=0x555555815a00, child_set=0x0) at /home/chopps/w/ly2/src/schema_compile_node.c:3380
#2  0x00007ffff7b1a187 in lys_compile_node (ctx=0x7fffffffbd70, pnode=0x5555558032d0, parent=0x555555815a00, uses_status=0, child_set=0x0) at /home/chopps/w/ly2/src/schema_compile_node.c:3711
#3  0x00007ffff7b16531 in lys_compile_node_list (ctx=0x7fffffffbd70, pnode=0x555555803230, node=0x555555815a00) at /home/chopps/w/ly2/src/schema_compile_node.c:2773
#4  0x00007ffff7b1a644 in lys_compile_node (ctx=0x7fffffffbd70, pnode=0x555555803230, parent=0x555555815980, uses_status=0, child_set=0x0) at /home/chopps/w/ly2/src/schema_compile_node.c:3782
#5  0x00007ffff7b140b7 in lys_compile_node_container (ctx=0x7fffffffbd70, pnode=0x555555803150, node=0x555555815980) at /home/chopps/w/ly2/src/schema_compile_node.c:2349
#6  0x00007ffff7b1a644 in lys_compile_node (ctx=0x7fffffffbd70, pnode=0x555555803150, parent=0x5555558117b0, uses_status=3, child_set=0x7fffffffb7e0) at /home/chopps/w/ly2/src/schema_compile_node.c:3782
#7  0x00007ffff7b18ab8 in lys_compile_uses (ctx=0x7fffffffbd70, uses_p=0x555555790e50, parent=0x5555558117b0, child_set=0x0) at /home/chopps/w/ly2/src/schema_compile_node.c:3406
#8  0x00007ffff7b1a187 in lys_compile_node (ctx=0x7fffffffbd70, pnode=0x555555790e50, parent=0x5555558117b0, uses_status=0, child_set=0x0) at /home/chopps/w/ly2/src/schema_compile_node.c:3711
#9  0x00007ffff7b16531 in lys_compile_node_list (ctx=0x7fffffffbd70, pnode=0x5555557902f0, node=0x5555558117b0) at /home/chopps/w/ly2/src/schema_compile_node.c:2773
#10 0x00007ffff7b1a644 in lys_compile_node (ctx=0x7fffffffbd70, pnode=0x5555557902f0, parent=0x555555810cd0, uses_status=0, child_set=0x0) at /home/chopps/w/ly2/src/schema_compile_node.c:3782
#11 0x00007ffff7b140b7 in lys_compile_node_container (ctx=0x7fffffffbd70, pnode=0x555555790210, node=0x555555810cd0) at /home/chopps/w/ly2/src/schema_compile_node.c:2349
#12 0x00007ffff7b1a644 in lys_compile_node (ctx=0x7fffffffbd70, pnode=0x555555790210, parent=0x555555807cb0, uses_status=0, child_set=0x0) at /home/chopps/w/ly2/src/schema_compile_node.c:3782
#13 0x00007ffff7b140b7 in lys_compile_node_container (ctx=0x7fffffffbd70, pnode=0x55555578f040, node=0x555555807cb0) at /home/chopps/w/ly2/src/schema_compile_node.c:2349
#14 0x00007ffff7b1a644 in lys_compile_node (ctx=0x7fffffffbd70, pnode=0x55555578f040, parent=0x5555558070f0, uses_status=0, child_set=0x7fffffffbc10) at /home/chopps/w/ly2/src/schema_compile_node.c:3782
#15 0x00007ffff7b254e0 in lys_compile_augment (ctx=0x7fffffffbd70, aug_p=0x55555579fbc8, target=0x5555558070f0) at /home/chopps/w/ly2/src/schema_compile_amend.c:1850
#16 0x00007ffff7b27583 in lys_precompile_augments_deviations (ctx=0x7fffffffbd70) at /home/chopps/w/ly2/src/schema_compile_amend.c:2284
#17 0x00007ffff7b06a7f in lys_compile (mod=0x55555578e470, options=0, unres=0x7fffffffcf80) at /home/chopps/w/ly2/src/schema_compile.c:1770
#18 0x00007ffff7b2c946 in lys_set_implemented_r (mod=0x55555578e470, features=0x7fffffffd040, unres=0x7fffffffcf80) at /home/chopps/w/ly2/src/tree_schema.c:708
#19 0x00007ffff7b2f265 in lys_create_module (ctx=0x555555769260, in=0x5555557741f0, format=LYS_IN_YANG, implement=1 '\001', custom_check=0x0, check_data=0x0, features=0x7fffffffd040, unres=0x7fffffffcf80, module=0x7fffffffd050) at /home/chopps/w/ly2/src/tree_schema.c:1233
#20 0x00007ffff7b2f5a1 in lys_parse (ctx=0x555555769260, in=0x5555557741f0, format=LYS_IN_YANG, features=0x7fffffffd040, module=0x7fffffffd050) at /home/chopps/w/ly2/src/tree_schema.c:1299
#21 0x00005555555581e4 in fill_context_inputs (argc=2, argv=0x7fffffffd5d8, c=0x7fffffffd410) at /home/chopps/w/ly2/tools/lint/main_ni.c:314
#22 0x0000555555558ffe in fill_context (argc=2, argv=0x7fffffffd5d8, c=0x7fffffffd410) at /home/chopps/w/ly2/tools/lint/main_ni.c:648
#23 0x0000555555559271 in main_ni (argc=2, argv=0x7fffffffd5d8) at /home/chopps/w/ly2/tools/lint/main_ni.c:691
#24 0x0000555555557c80 in main (argc=2, argv=0x7fffffffd5d8) at /home/chopps/w/ly2/tools/lint/main.c:45
```

**Comment by choppsv1** [comment]
I've got a simple reproduce case base on the above, I'll open a new issue.
