### ISSUE TITLE
ly2: segfault using LYD_LYB

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#1447]
Using libyang2 I wrote a program that does the following:
1 - Create a data tree by hand;
2 - Print that data tree to a buffer using `lyd_print_mem()` and the LYD_LYB data format;
3 - Parse that buffer (encoded using LYD_LYB) using `lyd_parse_data_mem()` to create a copy of the first data tree;
4 - Print the new data tree in the JSON format.

Here's what happens in the third step:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7ec6a69 in lyd_value_validate_incomplete (ctx=0x555555559260, type=0x555555586878, val=0x5555555d5d08, ctx_node=0x5555555d5cd0, tree=0x5555555a2a30) at /mnt/renato/git/northbound/lang-c/libyang2/src/tree_data.c:98
(gdb) bt
#0  0x00007ffff7ec6a69 in lyd_value_validate_incomplete (ctx=0x555555559260, type=0x555555586878, val=0x5555555d5d08, ctx_node=0x5555555d5cd0, tree=0x5555555a2a30) at /mnt/renato/git/northbound/lang-c/libyang2/src/tree_data.c:98
#1  0x00007ffff7f85c12 in lyd_validate_unres (tree=0x7fffffffe7e0, mod=0x555555561650, node_when=0x5555555d49c8, node_types=0x5555555d49a8, meta_types=0x5555555d49b8, diff=0x0) at /mnt/renato/git/northbound/lang-c/libyang2/src/validation.
c:257
#2  0x00007ffff7f889a0 in lyd_validate (tree=0x7fffffffe7e0, module=0x0, ctx=0x555555559260, val_opts=1, validate_subtree=0 '\000', node_when_p=0x5555555d49c8, node_types_p=0x5555555d49a8, meta_types_p=0x5555555d49b8, diff=0x0) at /mnt/re
nato/git/northbound/lang-c/libyang2/src/validation.c:1416
#3  0x00007ffff7ec77a1 in lyd_parse (ctx=0x555555559260, ext=0x0, parent=0x0, first_p=0x7fffffffe7e0, in=0x5555555b9f60, format=LYD_LYB, parse_opts=524288, val_opts=1, op=0x0) at /mnt/renato/git/northbound/lang-c/libyang2/src/tree_data.c:
360
#4  0x00007ffff7ec7bbd in lyd_parse_data (ctx=0x555555559260, parent=0x0, in=0x5555555b9f60, format=LYD_LYB, parse_options=524288, validate_options=1, tree=0x7fffffffe7e0) at /mnt/renato/git/northbound/lang-c/libyang2/src/tree_data.c:411
#5  0x00007ffff7ec7c2d in lyd_parse_data_mem (ctx=0x555555559260, data=0x5555555d5890 "lyb\020\004", format=LYD_LYB, parse_options=524288, validate_options=1, tree=0x7fffffffe7e0) at /mnt/renato/git/northbound/lang-c/libyang2/src/tree_dat
a.c:422
#6  0x0000555555555487 in main (argc=1, argv=0x7fffffffe908) at lyb_issue.c:60
(gdb) l
93              const struct lyd_node *ctx_node, const struct lyd_node *tree)
94      {
95          LY_ERR ret;
96          struct ly_err_item *err = NULL;
97
98          assert(type->plugin->validate);
99
100         ret = type->plugin->validate(ctx, type, ctx_node, tree, val, &err);
101         if (ret) {
102             if (err) {
(gdb) p type->plugin 
$2 = (struct lysc_type_plugin *) 0x0
```

If I change the data format to LYD_JSON in the second and third steps, then everything works normally.

Tarball containing a sample program and all required files necessary to reproduce the problem: [lyb_issue.tar.gz](https://github.com/CESNET/libyang/files/6086271/lyb_issue.tar.gz)

Any help would be appreciated!

**Comment by michalvasko** [comment]
Should be fixed.

**Comment by rwestphal** [comment]
It's working now. Thanks @michalvasko!
