### ISSUE TITLE
Build failure on Mac when using xcode cc

### ISSUE THREAD

**Issue by wlupton** [CESNET/libyang#1459]
I suspect this is a well-known problem and that I just don't know the proper answer.

When building on a Mac with xcode 12.4 (I've installed the command-line tools) I get the errors shown below. Based on other similar cases, I think I need the equivalent of these definitions:

```
CPPFLAGS += -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
LDFLAGS += -Xlinker -syslibroot -Xlinker /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
```

I could probably hack it, but probably there's a better way?

```
[  1%] Building C object CMakeFiles/compat.dir/compat/compat.c.o
/Users/william/Applications/libyang/compat/compat.c:64:13: error: implicitly declaring library function 'vsnprintf' with type 'int (char *, unsigned long, const char
      *, struct __va_list_tag *)' [-Werror,-Wimplicit-function-declaration]
    int l = vsnprintf(0, 0, fmt, ap2);
            ^
/Users/william/Applications/libyang/compat/compat.c:64:13: note: include the header <stdio.h> or explicitly provide a declaration for 'vsnprintf'
/Users/william/Applications/libyang/compat/compat.c:145:18: error: implicitly declaring library function 'strdup' with type 'char *(const char *)'
      [-Werror,-Wimplicit-function-declaration]
        retval = strdup(tmp);
                 ^
/Users/william/Applications/libyang/compat/compat.c:145:18: note: include the header <string.h> or explicitly provide a declaration for 'strdup'
2 errors generated.
```

**Comment by allena29** [comment]
I have just done a new install of big sur and hit this problem.

For libyang (v1.0.240) I skipped using Apple's Clang. It seems like from here it's a deliberate change Apple have made
https://developer.apple.com/forums/thread/655588?answerId=665804022#665804022

```
brew install cmake pcre llvm
export CC=/usr/local/opt/llvm/bin/clang
mkdir llvm && cd llvm
cmake ..
make && sudo make install

```

**Comment by TribuneX** [comment]
Any news on this issue? I though I was able to install Libyang on 12.0.1 based on your instructions with clang. However, I can't use it with the python binding, since installing the python binding gives me:

``` 
❯ pip3 install libyang        
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting libyang
  Downloading libyang-1.7.0.tar.gz (37 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cffi
  Using cached cffi-1.15.0-cp39-cp39-macosx_11_0_arm64.whl (173 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Building wheels for collected packages: libyang
  Building wheel for libyang (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/xxx/homebrew/opt/python@3.9/bin/python3.9 /Users/xxx/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/ph/r340bql55r18cpfjp45r855c0000gp/T/tmp2svvv7ok
       cwd: /private/var/folders/ph/r340bql55r18cpfjp45r855c0000gp/T/pip-install-wt0k11nc/libyang_f320173a9c5b4da593f901cacb015244
  Complete output (47 lines):
  Error processing line 1 of /private/var/folders/ph/r340bql55r18cpfjp45r855c0000gp/T/pip-build-env-ftpunsvm/overlay/lib/python3.9/site-packages/distutils-precedence.pth:
  
    Traceback (most recent call last):
      File "/Users/xxx/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site.py", line 169, in addpackage
        exec(line)
      File "<string>", line 1, in <module>
    AttributeError: module '_distutils_hack' has no attribute 'ensure_shim'
  
  Remainder of file ignored
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-12-arm64-3.9
  creating build/lib.macosx-12-arm64-3.9/libyang
  copying libyang/log.py -> build/lib.macosx-12-arm64-3.9/libyang
  copying libyang/util.py -> build/lib.macosx-12-arm64-3.9/libyang
  copying libyang/__init__.py -> build/lib.macosx-12-arm64-3.9/libyang
  copying libyang/context.py -> build/lib.macosx-12-arm64-3.9/libyang
  copying libyang/xpath.py -> build/lib.macosx-12-arm64-3.9/libyang
  copying libyang/diff.py -> build/lib.macosx-12-arm64-3.9/libyang
  copying libyang/keyed_list.py -> build/lib.macosx-12-arm64-3.9/libyang
  copying libyang/data.py -> build/lib.macosx-12-arm64-3.9/libyang
  copying libyang/schema.py -> build/lib.macosx-12-arm64-3.9/libyang
  running egg_info
  writing libyang.egg-info/PKG-INFO
  writing dependency_links to libyang.egg-info/dependency_links.txt
  writing requirements to libyang.egg-info/requires.txt
  writing top-level names to libyang.egg-info/top_level.txt
  reading manifest file 'libyang.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  writing manifest file 'libyang.egg-info/SOURCES.txt'
  copying libyang/VERSION -> build/lib.macosx-12-arm64-3.9/libyang
  copying libyang/py.typed -> build/lib.macosx-12-arm64-3.9/libyang
  running build_ext
  generating cffi module 'build/temp.macosx-12-arm64-3.9/_libyang.c'
  creating build/temp.macosx-12-arm64-3.9
  building '_libyang' extension
  creating build/temp.macosx-12-arm64-3.9/build
  creating build/temp.macosx-12-arm64-3.9/build/temp.macosx-12-arm64-3.9
  /Users/xxx/homebrew/opt/llvm/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I/Users/xxx/homebrew/include -I/Users/xxx/homebrew/opt/openssl@1.1/include -I/Users/xxx/homebrew/opt/sqlite/include -I/Users/xxx/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c build/temp.macosx-12-arm64-3.9/_libyang.c -o build/temp.macosx-12-arm64-3.9/build/temp.macosx-12-arm64-3.9/_libyang.o -Werror -std=c99
  build/temp.macosx-12-arm64-3.9/_libyang.c:574:10: fatal error: 'libyang/libyang.h' file not found
  #include <libyang/libyang.h>
           ^~~~~~~~~~~~~~~~~~~
  1 error generated.
  error: command '/Users/xxx/homebrew/opt/llvm/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for libyang
Failed to build libyang
ERROR: Could not build wheels for libyang, which is required to install pyproject.toml-based projects
```

**Comment by allena29** [comment]
I think of the Mac as a development environment and built my own wheels from the git project and pull them from a local pip server. A simple makefile forces libyang as a system dependency.

https://github.com/CESNET/libyang-python/issues/19 may be relevant.

**Comment by TribuneX** [comment]
Thanks, can you outline your setup in more detail? I found your linked issue in the python binding, but was not able to get it installed on my M1 Pro (see: https://github.com/CESNET/libyang-python/issues/19#issuecomment-1002161357)

**Comment by allena29** [comment]
> Thanks, can you outline your setup in more detail? I found your linked issue in the python binding, but was not able to get it installed on my M1 Pro (see: [CESNET/libyang-python#19 (comment)](https://github.com/CESNET/libyang-python/issues/19#issuecomment-1002161357))

I use x86_64 based Mac's - but use a local pyenv (this looks relevant for more recent Mac's https://laict.medium.com/install-python-on-macos-11-m1-apple-silicon-using-pyenv-12e0729427a9).

Once in the virtualenv (I've tried 3.7/3.9/3.10) -  `pip3 install wheel` followed by `python3 setup.py build bdist_wheel` - that gives a libyang whl for a specific OS/Architecture in the dist directory that can be installed as `python3 -m pip install <filename>`.

Old versions of libyang-cffi built a static version of the C library into the python wheel (so required `LIBYANG_INSTALL=system`) but that's recently been removed.

**Comment by TribuneX** [comment]
Thx. I just got it working using `gcc-11` installed via homebrew. I was able to successfully install libyang and afterwards the python binding.
