### ISSUE TITLE
ly2: segmentation fault in lyd_validate_module

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libyang#1474]
Hi,

I have issue with the following YANG model on libyang2 branch:

```
module test {
  yang-version 1.1;
  namespace "urn:com:test";
  prefix t;

  import ietf-interfaces {
    prefix if;
  }
  
  import iana-if-type {
    prefix ianaift;
  }
  
  revision 2021-03-26 {
    description
      "Initial version";
  }

  augment "/if:interfaces/if:interface" {
  when "derived-from-or-self(if:type, 'ianaift:ethernetCsmacd') and " +
       "re-match(if:name, 'T .*')";
    
    container testconfig {
      leaf config1 {
        type string;
      }
    }
  }
}
```

When this module is installed and I try to create a new ethernetCsmacd instance in sysrepo, I get a segmentation fault:

```
$ sysrepocfg --import=config.xml -d running -m ietf-interfaces
Segmentation fault (core dumped)

```
config.xml content:
```
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>eth0</name>
    <description>Test interface</description>
    <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
  </interface>
</interfaces>
```

Stack trace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff78470e5 in ly_err_new (err=0x7fffffffcdf8, ecode=LY_EVALID, vecode=LYVE_SUCCESS, path=0x0, apptag=0x0, err_msg=0x7ffff7937c78 "Unsatisfied pattern - \"%.*s\" does not conform to %s\"%s\".")
    at /opt/dev/libyang/src/log.c:137
137	/opt/dev/libyang/src/log.c: No such file or directory.
(gdb) bt
#0  0x00007ffff78470e5 in ly_err_new (err=0x7fffffffcdf8, ecode=LY_EVALID, vecode=LYVE_SUCCESS, path=0x0, apptag=0x0, err_msg=0x7ffff7937c78 "Unsatisfied pattern - \"%.*s\" does not conform to %s\"%s\".")
    at /opt/dev/libyang/src/log.c:137
#1  0x00007ffff78fd0e0 in ly_type_validate_patterns (patterns=0x555555779278, str=0x5555557e2210 "eth0", str_len=4, err=0x7fffffffcdf8) at /opt/dev/libyang/src/plugins_types.c:491
#2  0x00007ffff79139d1 in xpath_re_match (args=0x555555779290, UNUSED_arg_count=2, set=0x7fffffffd000, options=2) at /opt/dev/libyang/src/xpath.c:4614
#3  0x00007ffff791bf64 in eval_function_call (exp=0x5555557ee760, tok_idx=0x7fffffffd132, set=0x7fffffffd000, options=2) at /opt/dev/libyang/src/xpath.c:7619
#4  0x00007ffff791c5f4 in eval_path_expr (exp=0x5555557ee760, tok_idx=0x7fffffffd132, set=0x7fffffffd000, options=2) at /opt/dev/libyang/src/xpath.c:7737
#5  0x00007ffff791e981 in eval_expr_select (exp=0x5555557ee760, tok_idx=0x7fffffffd132, etype=LYXP_EXPR_AND, set=0x7fffffffd000, options=2) at /opt/dev/libyang/src/xpath.c:8402
#6  0x00007ffff791e260 in eval_and_expr (exp=0x5555557ee760, tok_idx=0x7fffffffd132, repeat=1, set=0x7fffffffd1c0, options=2) at /opt/dev/libyang/src/xpath.c:8249
#7  0x00007ffff791e884 in eval_expr_select (exp=0x5555557ee760, tok_idx=0x7fffffffd132, etype=LYXP_EXPR_NONE, set=0x7fffffffd1c0, options=2) at /opt/dev/libyang/src/xpath.c:8381
#8  0x00007ffff791edc7 in lyxp_eval (ctx=0x55555575b500, exp=0x5555557ee760, cur_mod=0x5555557ef300, format=LY_PREF_SCHEMA_RESOLVED, prefix_data=0x5555557c3fa8, ctx_node=0x555555788750, tree=0x555555788700, 
    set=0x7fffffffd1c0, options=2) at /opt/dev/libyang/src/xpath.c:8493
#9  0x00007ffff791fe3f in lyd_validate_node_when (tree=0x555555788700, node=0x555555799230, schema=0x5555557c3160, disabled=0x7fffffffd288) at /opt/dev/libyang/src/validation.c:135
#10 0x00007ffff791ffd3 in lyd_validate_unres_when (tree=0x7fffffffd570, mod=0x5555557d8150, node_when=0x7fffffffd3c0, diff=0x7fffffffd478) at /opt/dev/libyang/src/validation.c:187
#11 0x00007ffff7920183 in lyd_validate_unres (tree=0x7fffffffd570, mod=0x5555557d8150, node_when=0x7fffffffd3c0, node_types=0x7fffffffd3a0, meta_types=0x7fffffffd3b0, diff=0x7fffffffd478)
    at /opt/dev/libyang/src/validation.c:240
#12 0x00007ffff7923251 in lyd_validate (tree=0x7fffffffd570, module=0x5555557d8150, ctx=0x55555575b500, val_opts=1, validate_subtree=1 '\001', node_when_p=0x7fffffffd3c0, node_types_p=0x7fffffffd3a0, 
    meta_types_p=0x7fffffffd3b0, diff=0x7fffffffd478) at /opt/dev/libyang/src/validation.c:1418
#13 0x00007ffff7923542 in lyd_validate_module (tree=0x7fffffffd570, module=0x5555557d8150, val_opts=1, diff=0x7fffffffd478) at /opt/dev/libyang/src/validation.c:1455
#14 0x00007ffff7b849a4 in sr_modinfo_validate (mod_info=0x7fffffffd560, mod_state=258, finish_diff=1) at /opt/dev/sysrepo/src/modinfo.c:1887
#15 0x00007ffff7b66a44 in sr_changes_notify_store (mod_info=0x7fffffffd560, session=0x555555792ba0, timeout_ms=5000, cb_err_info=0x7fffffffd548) at /opt/dev/sysrepo/src/sysrepo.c:2001
#16 0x00007ffff7b674ba in _sr_replace_config (session=0x555555792ba0, ly_mod=0x5555557d8150, src_config=0x7fffffffd5b8, timeout_ms=5000) at /opt/dev/sysrepo/src/sysrepo.c:2295
#17 0x00007ffff7b676e4 in sr_replace_config (session=0x555555792ba0, module_name=0x7fffffffded2 "ietf-interfaces", src_config=0x0, timeout_ms=5000, wait=1) at /opt/dev/sysrepo/src/sysrepo.c:2342
#18 0x0000555555556692 in op_import (sess=0x555555792ba0, file_path=0x7fffffffde91 "./sysrepo-issues/libyang2-when-segfault/config.xml", module_name=0x7fffffffded2 "ietf-interfaces", format=LYD_UNKNOWN, 
    not_strict=0, timeout_s=0) at /opt/dev/sysrepo/src/executables/sysrepocfg.c:333
#19 0x0000555555557b24 in main (argc=6, argv=0x7fffffffda68) at /opt/dev/sysrepo/src/executables/sysrepocfg.c:895
```

Without `re-match(if:name, 'T .*')` the operation succeeds.

libyang version: d43298b161802b52f0a4daacd607fcba30f34bea
sysrepo version: 41e2bf970438de1c3d2260f022472b537c8101b5

Installed yang modules:
```
iana-if-type               | 2018-07-03
ietf-interfaces            | 2018-02-20 
test                       | 2021-03-26
```

Thanks!

**Comment by awesomenode** [comment]
It works on the fixed version, thanks!
