### ISSUE TITLE
ly2: segmentation fault in node_ext_tovalidate_add

### ISSUE THREAD

**Issue by awesomenode** [CESNET/libyang#1492]
Hi,

I get segmentation fault during installation of custom yang models:
 
```
Thread 1 "test" received signal SIGSEGV, Segmentation fault.
0x00007ffff71ecd4e in node_ext_tovalidate_add (node_exts=0x7fffffffd120, exts=0x555555a0ac98, node=0x555555b23c20) at /opt/dev/libyang/src/validation.c:241
241     /opt/dev/libyang/src/validation.c: No such file or directory.
(gdb) bt
#0  0x00007ffff71ecd4e in node_ext_tovalidate_add (node_exts=0x7fffffffd120, exts=0x555555a0ac98, node=0x555555b23c20) at /opt/dev/libyang/src/validation.c:241
#1  0x00007ffff71ece99 in lysc_node_ext_tovalidate (node_exts=0x7fffffffd120, node=0x555555b23c20) at /opt/dev/libyang/src/validation.c:269
#2  0x00007ffff71efcf1 in lyd_validate_subtree (root=0x555555b23bd0, node_when=0x7fffffffd110, node_exts=0x7fffffffd120, node_types=0x7fffffffd0f0, meta_types=0x7fffffffd100, impl_opts=1, diff=0x0)
    at /opt/dev/libyang/src/validation.c:1418
#3  0x00007ffff71f0162 in lyd_validate (tree=0x7fffffffd1e8, module=0x0, ctx=0x5555557e3a90, val_opts=1, validate_subtree=1 '\001', node_when_p=0x7fffffffd110, node_exts_p=0x7fffffffd120, 
    node_types_p=0x7fffffffd0f0, meta_types_p=0x7fffffffd100, diff=0x0) at /opt/dev/libyang/src/validation.c:1483
#4  0x00007ffff71f03af in lyd_validate_all (tree=0x7fffffffd1e8, ctx=0x5555557e3a90, val_opts=1, diff=0x0) at /opt/dev/libyang/src/validation.c:1517
#5  0x00007ffff745ffa2 in sr_lydmods_sched_update_data (sr_mods=0x5555558918d0, new_ctx=0x5555557e3a90, fail=0x7fffffffd2e4) at /opt/dev/sysrepo/src/lyd_mods.c:1444
#6  0x00007ffff74618b2 in sr_lydmods_sched_apply (sr_mods=0x5555558918d0, new_ctx=0x5555557e3a90, change=0x7fffffffd2dc, fail=0x7fffffffd2e4) at /opt/dev/sysrepo/src/lyd_mods.c:2045
#7  0x00007ffff7461f06 in sr_lydmods_conn_ctx_update (main_shm=0x7ffff7fe3000, ly_ctx=0x5555558566b0, apply_sched=1, err_on_sched_fail=0, changed=0x7fffffffd33c) at /opt/dev/sysrepo/src/lyd_mods.c:2171
#8  0x00007ffff7430d0b in sr_connect (opts=1, conn_p=0x7fffffffd4e0) at /opt/dev/sysrepo/src/sysrepo.c:174
```
 
There is a NULL pointer dereference because the value of `ext->def->plugin` is NULL at validation.c:241.
Adding a NULL check to if condition solves the issue for me.
 
sysrepo version: 2dec6b2263dcca062a3eeca60a249b27da4021cb
libyang version: be51c94825ea2e35fe4312f36f22af641774c893

Thanks!

**Comment by awesomenode** [comment]
The segmentation fault is gone on the latest version, thanks!
