### ISSUE TITLE
`ly_ctx_destroy()` and others cause UB

### ISSUE THREAD

**Issue by syyyr** [CESNET/libyang#1611]
This program:
```c
#include <libyang/libyang.h>
int main()
{
    struct ly_ctx* ctx;
    ly_ctx_new(NULL, 0, &ctx);
    ly_ctx_destroy(ctx);
}
```
when compiled with UndefinedBehaviorSanitizer causes some errors:
```
$ ./a.out 
/home/vk/git/libyang/src/tree_schema_free.c:371:9: runtime error: member access within null pointer of type 'struct lysp_node_grp'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/libyang/src/tree_schema_free.c:371:9 in 
/home/vk/git/libyang/src/tree_schema_free.c:371:9: runtime error: member access within null pointer of type 'union lysp_node_grp::(anonymous at /home/vk/git/libyang/src/tree_schema.h:1253:5)'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/libyang/src/tree_schema_free.c:371:9 in 
/home/vk/git/libyang/src/tree_schema_free.c:402:9: runtime error: member access within null pointer of type 'struct lysp_node_augment'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/libyang/src/tree_schema_free.c:402:9 in 
/home/vk/git/libyang/src/tree_schema_free.c:402:9: runtime error: member access within null pointer of type 'union lysp_node_augment::(anonymous at /home/vk/git/libyang/src/tree_schema.h:1280:5)'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/libyang/src/tree_schema_free.c:402:9 in 
/home/vk/git/libyang/src/tree_schema_free.c:377:9: runtime error: member access within null pointer of type 'struct lysp_node_action'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/libyang/src/tree_schema_free.c:377:9 in 
/home/vk/git/libyang/src/tree_schema_free.c:377:9: runtime error: member access within null pointer of type 'union lysp_node_action::(anonymous at /home/vk/git/libyang/src/tree_schema.h:1200:5)'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/libyang/src/tree_schema_free.c:377:9 in 
/home/vk/git/libyang/src/tree_schema_free.c:380:9: runtime error: member access within null pointer of type 'struct lysp_node_notif'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/libyang/src/tree_schema_free.c:380:9 in 
/home/vk/git/libyang/src/tree_schema_free.c:380:9: runtime error: member access within null pointer of type 'union lysp_node_notif::(anonymous at /home/vk/git/libyang/src/tree_schema.h:1227:5)'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/libyang/src/tree_schema_free.c:380:9 in 
/home/vk/git/libyang/src/tree_schema_free.c:345:9: runtime error: member access within null pointer of type 'struct lysp_node_grp'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/libyang/src/tree_schema_free.c:345:9 in 
/home/vk/git/libyang/src/tree_schema_free.c:345:9: runtime error: member access within null pointer of type 'union lysp_node_grp::(anonymous at /home/vk/git/libyang/src/tree_schema.h:1253:5)'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/libyang/src/tree_schema_free.c:345:9 in 
/home/vk/git/libyang/src/tree_schema_free.c:351:9: runtime error: member access within null pointer of type 'struct lysp_node_action'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/libyang/src/tree_schema_free.c:351:9 in 
/home/vk/git/libyang/src/tree_schema_free.c:351:9: runtime error: member access within null pointer of type 'union lysp_node_action::(anonymous at /home/vk/git/libyang/src/tree_schema.h:1200:5)'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/libyang/src/tree_schema_free.c:351:9 in 
/home/vk/git/libyang/src/tree_schema_free.c:354:9: runtime error: member access within null pointer of type 'struct lysp_node_notif'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/libyang/src/tree_schema_free.c:354:9 in 
/home/vk/git/libyang/src/tree_schema_free.c:354:9: runtime error: member access within null pointer of type 'union lysp_node_notif::(anonymous at /home/vk/git/libyang/src/tree_schema.h:1227:5)'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/libyang/src/tree_schema_free.c:354:9 in 
/home/vk/git/libyang/src/tree_schema_free.c:432:9: runtime error: member access within null pointer of type 'struct lysp_node_grp'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/libyang/src/tree_schema_free.c:432:9 in 
/home/vk/git/libyang/src/tree_schema_free.c:432:9: runtime error: member access within null pointer of type 'union lysp_node_grp::(anonymous at /home/vk/git/libyang/src/tree_schema.h:1253:5)'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/libyang/src/tree_schema_free.c:432:9 in 
```

**Comment by michalvasko** [comment]
I cannot reproduce it (we run all the tests with ASAN and UBSAN in our CI) so it will be specific for your platform. Because of that I am not really sure how to fix it so that the sanitizer is happy. I am inclined to think this is harmless and the sanitizer just has problems with the special way the structures are defined. So I would appreciate some help, should not be difficult to fix.

**Comment by syyyr** [comment]
I'm running Arch Linux and my Clang version is 12.0.0 (your CI seems to run 9.0.0).

This isn't a blocker for me. I'll look at it later. Thanks for now.

**Comment by michalvasko** [comment]
Fine, just note that I have tried it with Clang 12 on OpenSUSE Tumbleweed, saw no errors.

**Comment by syyyr** [comment]
Okay, I think I found out what UBSan's problem is. It's actually pretty simple, this is one of the problem lines in `tree_schema_free.c:371`
```c
LY_LIST_FOR_SAFE(&((struct lysp_node_list *)node)->groupings->node, next, child) {
    lysp_node_free(ctx, child);
}
```
I have put some print statements before it:
```c
fprintf(stderr, "node = %p\n", node);
fprintf(stderr, "((struct lysp_node_list *)node) = %p\n", ((struct lysp_node_list *)node));
fprintf(stderr, "((struct lysp_node_list *)node)->groupings = %p\n", ((struct lysp_node_list *)node)->groupings);
fprintf(stderr, "((struct lysp_node_list *)node)->groupings->node = %p\n", &((struct lysp_node_list *)node)->groupings->node);
LY_LIST_FOR_SAFE(&((struct lysp_node_list *)node)->groupings->node, next, child) {
    lysp_node_free(ctx, child);
}
```
This is the output:
```
node = 0x60d000003e00
((struct lysp_node_list *)node) = 0x60d000003e00
((struct lysp_node_list *)node)->groupings = (nil)
/home/vk/git/libyang/src/tree_schema_free.c:374:129: runtime error: member access within null pointer of type 'struct lysp_node_grp'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/libyang/src/tree_schema_free.c:374:129 in 
/home/vk/git/libyang/src/tree_schema_free.c:374:129: runtime error: member access within null pointer of type 'union lysp_node_grp::(anonymous at /home/vk/git/libyang/src/tree_schema.h:1253:5)'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/libyang/src/tree_schema_free.c:374:129 in 
((struct lysp_node_list *)node)->groupings->node = (nil)
```
As can be seen, the code dereferences the `groupings` field, but this field is `NULL`. I'm not sure why this doesn't cause a crash, but I guess it just doesn't.

Anyway: putting an if-statement around the macro does solve the issue (for this macro call). Like this:
```c
if (((struct lysp_node_list *)node)->groupings) {
    LY_LIST_FOR_SAFE(&((struct lysp_node_list *)node)->groupings->node, next, child) {
        lysp_node_free(ctx, child);
    }
}
```

**Comment by michalvasko** [comment]
It is probably like I said, the compiler is generally smart enough to avoid accessing NULL pointer in the actual binary because `groupings->node` is just a substructure of `groupings`, is used instead of casts. But I have added the checks, they do no harm, so now it should work for you, too.

**Comment by syyyr** [comment]
Hi, thanks for the fixes. I appreciate that you added the checks.

Anyway, there are some more errors by UBSan. Here's a log from running the whole test suite (some of the errors are similar, but there are also others like passing a NULL inside some functions):
```
$ UBSAN_OPTIONS=halt_on_error=1 ctest -E format -j16 --output-on-failure 
Test project /home/vk/git/lol/submodules/dependencies/libyang/build-au
      Start  2: utest_int8
      Start  3: utest_string
      Start  4: utest_bits
      Start  7: utest_yang_types
      Start 10: utest_list
      Start 19: utest_xpath
      Start 28: utest_tree_data
      Start 32: utest_parser_json
      Start 33: utest_lyb
      Start 34: utest_validation
      Start 35: utest_types
      Start 36: utest_merge
      Start 37: utest_diff
      Start 40: utest_yangdata
      Start 41: regress_fuzz_lys_parse_mem
      Start 24: utest_tree_schema_compile
 1/44 Test #28: utest_tree_data ...................***Failed    0.06 sec
[==========] Running 7 test(s).
[ RUN      ] test_compare
/home/vk/git/lol/submodules/dependencies/libyang/src/parser_yang.c:2064:22: runtime error: null pointer passed as argument 2, which is declared to never be null
/usr/include/string.h:48:14: note: nonnull attribute specified here
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/lol/submodules/dependencies/libyang/src/parser_yang.c:2064:22 in 

      Start 23: utest_parser_yin
 2/44 Test #34: utest_validation ..................***Failed    0.06 sec
[==========] Running 12 test(s).
[ RUN      ] test_when
/home/vk/git/lol/submodules/dependencies/libyang/src/tree_data.h:982:27: runtime error: member access within null pointer of type 'struct lyd_node_inner'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/lol/submodules/dependencies/libyang/src/tree_data.h:982:27 in 

      Start 25: utest_printer_tree
 3/44 Test  #7: utest_yang_types ..................***Failed    0.10 sec
[==========] Running 2 test(s).
[ RUN      ] test_data_xml
[       OK ] test_data_xml
[ RUN      ] test_print
/home/vk/git/lol/submodules/dependencies/libyang/src/parser_json.c:205:5: runtime error: member access within null pointer of type 'const struct lyd_node_inner'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/lol/submodules/dependencies/libyang/src/parser_json.c:205:5 in 

      Start 43: regress_fuzz_lyd_parse_mem_json
 4/44 Test #32: utest_parser_json .................***Failed    0.10 sec
[==========] Running 10 test(s).
[ RUN      ] test_leaf
/home/vk/git/lol/submodules/dependencies/libyang/src/parser_json.c:205:5: runtime error: member access within null pointer of type 'const struct lyd_node_inner'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/lol/submodules/dependencies/libyang/src/parser_json.c:205:5 in 

      Start 42: regress_fuzz_lyd_parse_mem_xml
 5/44 Test #36: utest_merge .......................***Failed    0.10 sec
[==========] Running 11 test(s).
[ RUN      ] test_batch
[       OK ] test_batch
[ RUN      ] test_leaf
/home/vk/git/lol/submodules/dependencies/libyang/src/tree_data.c:3442:49: runtime error: member access within null pointer of type 'struct lyd_node_inner'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/lol/submodules/dependencies/libyang/src/tree_data.c:3442:49 in 

      Start 15: utest_context
 6/44 Test #37: utest_diff ........................***Failed    0.14 sec
[==========] Running 14 test(s).
[ RUN      ] test_invalid
[       OK ] test_invalid
[ RUN      ] test_same
[       OK ] test_same
[ RUN      ] test_empty1
/home/vk/git/lol/submodules/dependencies/libyang/src/tree_data.c:3442:49: runtime error: member access within null pointer of type 'struct lyd_node_inner'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/lol/submodules/dependencies/libyang/src/tree_data.c:3442:49 in 

      Start 22: utest_parser_yang
 7/44 Test #19: utest_xpath .......................***Failed    0.16 sec
[==========] Running 5 test(s).
[ RUN      ] test_hash
[       OK ] test_hash
[ RUN      ] test_toplevel
[       OK ] test_toplevel
[ RUN      ] test_atomize
[       OK ] test_atomize
[ RUN      ] test_canonize
/home/vk/git/lol/submodules/dependencies/libyang/src/tree_data.h:982:27: runtime error: member access within null pointer of type 'struct lyd_node_inner'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/lol/submodules/dependencies/libyang/src/tree_data.h:982:27 in 

      Start  1: headers
 8/44 Test  #4: utest_bits ........................***Failed    0.19 sec
[==========] Running 11 test(s).
[ RUN      ] test_schema_yang
[       OK ] test_schema_yang
[ RUN      ] test_schema_yin
[       OK ] test_schema_yin
[ RUN      ] test_schema_print
[       OK ] test_schema_print
[ RUN      ] test_data_xml
/home/vk/git/lol/submodules/dependencies/libyang/src/plugins_types/bits.c:233:44: runtime error: left shift of negative value -128
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/lol/submodules/dependencies/libyang/src/plugins_types/bits.c:233:44 in 

      Start 30: utest_parser_xml
 9/44 Test #10: utest_list ........................***Failed    0.23 sec
[==========] Running 7 test(s).
[ RUN      ] test_schema_yang
[       OK ] test_schema_yang
[ RUN      ] test_schema_yin
[       OK ] test_schema_yin
[ RUN      ] test_schema_print
[       OK ] test_schema_print
[ RUN      ] test_xml
[       OK ] test_xml
[ RUN      ] test_json
/home/vk/git/lol/submodules/dependencies/libyang/src/parser_json.c:205:5: runtime error: member access within null pointer of type 'const struct lyd_node_inner'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/lol/submodules/dependencies/libyang/src/parser_json.c:205:5 in 

      Start 21: utest_schema
10/44 Test #33: utest_lyb .........................***Failed    0.22 sec
[==========] Running 3 test(s).
[ RUN      ] test_ietf_interfaces
[       OK ] test_ietf_interfaces
[ RUN      ] test_origin
[       OK ] test_origin
[ RUN      ] test_statements
/home/vk/git/lol/submodules/dependencies/libyang/src/tree_data.h:982:27: runtime error: member access within null pointer of type 'struct lyd_node_inner'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/lol/submodules/dependencies/libyang/src/tree_data.h:982:27 in 

      Start 14: utest_inout
11/44 Test #40: utest_yangdata ....................***Failed    0.23 sec
[==========] Running 3 test(s).
[ RUN      ] test_schema
[       OK ] test_schema
[ RUN      ] test_schema_invalid
[       OK ] test_schema_invalid
[ RUN      ] test_data
/home/vk/git/lol/submodules/dependencies/libyang/src/parser_json.c:205:5: runtime error: member access within null pointer of type 'const struct lyd_node_inner'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/lol/submodules/dependencies/libyang/src/parser_json.c:205:5 in 

      Start 44: yanglint_ni_list
12/44 Test  #3: utest_string ......................***Failed    0.27 sec
[==========] Running 11 test(s).
[ RUN      ] test_schema_yang
[       OK ] test_schema_yang
[ RUN      ] test_schema_yin
[       OK ] test_schema_yin
[ RUN      ] test_schema_print
[       OK ] test_schema_print
[ RUN      ] test_data_xml
[       OK ] test_data_xml
[ RUN      ] test_data_json
/home/vk/git/lol/submodules/dependencies/libyang/src/parser_json.c:205:5: runtime error: member access within null pointer of type 'const struct lyd_node_inner'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/lol/submodules/dependencies/libyang/src/parser_json.c:205:5 in 

      Start 17: utest_xml
13/44 Test  #2: utest_int8 ........................***Failed    0.36 sec
[==========] Running 11 test(s).
[ RUN      ] test_schema_yang
[       OK ] test_schema_yang
[ RUN      ] test_schema_yin
[       OK ] test_schema_yin
[ RUN      ] test_schema_print
[       OK ] test_schema_print
[ RUN      ] test_data_xml
[       OK ] test_data_xml
[ RUN      ] test_data_json
/home/vk/git/lol/submodules/dependencies/libyang/src/parser_json.c:205:5: runtime error: member access within null pointer of type 'const struct lyd_node_inner'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/lol/submodules/dependencies/libyang/src/parser_json.c:205:5 in 

      Start 11: utest_common
14/44 Test #35: utest_types .......................***Failed    0.39 sec
[==========] Running 10 test(s).
[ RUN      ] test_int
[       OK ] test_int
[ RUN      ] test_uint
[       OK ] test_uint
[ RUN      ] test_dec64
[       OK ] test_dec64
[ RUN      ] test_enums
[       OK ] test_enums
[ RUN      ] test_boolean
[       OK ] test_boolean
[ RUN      ] test_empty
[       OK ] test_empty
[ RUN      ] test_identityref
[       OK ] test_identityref
[ RUN      ] test_instanceid
[       OK ] test_instanceid
[ RUN      ] test_leafref
/home/vk/git/lol/submodules/dependencies/libyang/src/tree_data.h:982:27: runtime error: member access within null pointer of type 'struct lyd_node_inner'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/lol/submodules/dependencies/libyang/src/tree_data.h:982:27 in 

      Start 12: utest_set
15/44 Test #17: utest_xml .........................   Passed    0.22 sec
      Start 31: utest_printer_xml
16/44 Test #44: yanglint_ni_list ..................   Passed    0.28 sec
      Start 18: utest_json
17/44 Test #14: utest_inout .......................   Passed    0.33 sec
      Start 13: utest_hash_table
18/44 Test #11: utest_common ......................   Passed    0.21 sec
      Start 29: utest_new
19/44 Test #12: utest_set .........................   Passed    0.20 sec
      Start  8: utest_range
20/44 Test #31: utest_printer_xml .................   Passed    0.19 sec
      Start 16: utest_plugins
21/44 Test #30: utest_parser_xml ..................   Passed    0.53 sec
      Start 39: utest_nacm
22/44 Test  #1: headers ...........................   Passed    0.55 sec
      Start  9: utest_pattern
23/44 Test #18: utest_json ........................   Passed    0.19 sec
      Start 38: utest_metadata
24/44 Test #13: utest_hash_table ..................   Passed    0.18 sec
      Start 27: utest_printer_yin
25/44 Test #21: utest_schema ......................   Passed    0.51 sec
      Start 26: utest_printer_yang
26/44 Test #29: utest_new .........................   Passed    0.19 sec
      Start 20: utest_yanglib
27/44 Test  #8: utest_range .......................   Passed    0.19 sec
      Start  5: utest_binary
28/44 Test #20: utest_yanglib .....................   Passed    0.08 sec
      Start  6: utest_inet_types
29/44 Test #26: utest_printer_yang ................   Passed    0.10 sec
30/44 Test #27: utest_printer_yin .................   Passed    0.11 sec
31/44 Test #16: utest_plugins .....................   Passed    0.18 sec
32/44 Test  #5: utest_binary ......................   Passed    0.06 sec
33/44 Test  #9: utest_pattern .....................   Passed    0.17 sec
34/44 Test #39: utest_nacm ........................   Passed    0.18 sec
35/44 Test #38: utest_metadata ....................   Passed    0.16 sec
36/44 Test  #6: utest_inet_types ..................   Passed    0.06 sec
37/44 Test #15: utest_context .....................   Passed    0.81 sec
38/44 Test #22: utest_parser_yang .................   Passed    0.77 sec
39/44 Test #42: regress_fuzz_lyd_parse_mem_xml ....   Passed    0.93 sec
40/44 Test #25: utest_printer_tree ................   Passed    1.02 sec
41/44 Test #43: regress_fuzz_lyd_parse_mem_json ...   Passed    1.00 sec
42/44 Test #23: utest_parser_yin ..................   Passed    1.68 sec
43/44 Test #24: utest_tree_schema_compile .........   Passed    2.14 sec
44/44 Test #41: regress_fuzz_lys_parse_mem ........   Passed    3.59 sec

68% tests passed, 14 tests failed out of 44

Total Test time (real) =   3.63 sec

The following tests FAILED:
	  2 - utest_int8 (Failed)
	  3 - utest_string (Failed)
	  4 - utest_bits (Failed)
	  7 - utest_yang_types (Failed)
	 10 - utest_list (Failed)
	 19 - utest_xpath (Failed)
	 28 - utest_tree_data (Failed)
	 32 - utest_parser_json (Failed)
	 33 - utest_lyb (Failed)
	 34 - utest_validation (Failed)
	 35 - utest_types (Failed)
	 36 - utest_merge (Failed)
	 37 - utest_diff (Failed)
	 40 - utest_yangdata (Failed)
Errors while running CTest
```

**Comment by michalvasko** [comment]
Okay, the warnings should be fixed now.

**Comment by syyyr** [comment]
I still got two more. I didn't catch those, because I was using `UBSAN_OPTIONS=halt_on_error=0`. So the tests ended prematurely. Hopefully, those will be last. Thank you very much for fixing these.
```
$ ctest -R  utest_types -V; ctest -R utest_yangdata -V
UpdateCTestConfiguration  from :/home/vk/git/lol/submodules/dependencies/libyang/build-au/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/vk/git/lol/submodules/dependencies/libyang/build-au/DartConfiguration.tcl
Test project /home/vk/git/lol/submodules/dependencies/libyang/build-au
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 36
    Start 36: utest_types

36: Test command: /home/vk/git/lol/submodules/dependencies/libyang/build-au/tests/utest_types
36: Environment variables: 
36:  MALLOC_CHECK_=3
36: Test timeout computed to be: 10000000
36: [==========] Running 10 test(s).
36: [ RUN      ] test_int
36: [       OK ] test_int
36: [ RUN      ] test_uint
36: [       OK ] test_uint
36: [ RUN      ] test_dec64
36: [       OK ] test_dec64
36: [ RUN      ] test_enums
36: [       OK ] test_enums
36: [ RUN      ] test_boolean
36: [       OK ] test_boolean
36: [ RUN      ] test_empty
36: [       OK ] test_empty
36: [ RUN      ] test_identityref
36: [       OK ] test_identityref
36: [ RUN      ] test_instanceid
36: [       OK ] test_instanceid
36: [ RUN      ] test_leafref
36: /home/vk/git/lol/submodules/dependencies/libyang/src/xpath.c:930:32: runtime error: null pointer passed as argument 2, which is declared to never be null
36: /usr/include/string.h:44:28: note: nonnull attribute specified here
36: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/lol/submodules/dependencies/libyang/src/xpath.c:930:32 in 
1/1 Test #36: utest_types ......................***Failed    0.17 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.17 sec

The following tests FAILED:
	 36 - utest_types (Failed)
Errors while running CTest
Output from these tests are in: /home/vk/git/lol/submodules/dependencies/libyang/build-au/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
UpdateCTestConfiguration  from :/home/vk/git/lol/submodules/dependencies/libyang/build-au/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/vk/git/lol/submodules/dependencies/libyang/build-au/DartConfiguration.tcl
Test project /home/vk/git/lol/submodules/dependencies/libyang/build-au
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 41
    Start 41: utest_yangdata

41: Test command: /home/vk/git/lol/submodules/dependencies/libyang/build-au/tests/utest_yangdata
41: Environment variables: 
41:  MALLOC_CHECK_=3
41: Test timeout computed to be: 10000000
41: [==========] Running 3 test(s).
41: [ RUN      ] test_schema
41: [       OK ] test_schema
41: [ RUN      ] test_schema_invalid
41: [       OK ] test_schema_invalid
41: [ RUN      ] test_data
41: /home/vk/git/lol/submodules/dependencies/libyang/src/parser_json.c:853:34: runtime error: member access within null pointer of type 'struct lyd_node_inner'
41: SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vk/git/lol/submodules/dependencies/libyang/src/parser_json.c:853:34 in 
1/1 Test #41: utest_yangdata ...................***Failed    0.11 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.11 sec

The following tests FAILED:
	 41 - utest_yangdata (Failed)
Errors while running CTest
Output from these tests are in: /home/vk/git/lol/submodules/dependencies/libyang/build-au/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

**Comment by michalvasko** [comment]
This should be fixed and I also tried to find all possible problems with `memcpy` and `memmove`.

**Comment by jktjkt** [comment]
Here's one more:
```
/home/ci/src/cesnet-gerrit-public/github/CESNET/libyang/src/parser_json.c:903:38: runtime error: member access within null pointer of type 'struct lyd_node_inner'
    #0 0x64d7b5 in lydjson_create_opaq /home/ci/src/cesnet-gerrit-public/github/CESNET/libyang/src/parser_json.c:903:38
    #1 0x64bd67 in lydjson_parse_opaq /home/ci/src/cesnet-gerrit-public/github/CESNET/libyang/src/parser_json.c:943:11
    #2 0x6447dd in lydjson_ctx_next_parse_opaq /home/ci/src/cesnet-gerrit-public/github/CESNET/libyang/src/parser_json.c:1030:5
    #3 0x644191 in lydjson_parse_attribute /home/ci/src/cesnet-gerrit-public/github/CESNET/libyang/src/parser_json.c:1081:15
    #4 0x63b508 in lydjson_subtree_r /home/ci/src/cesnet-gerrit-public/github/CESNET/libyang/src/parser_json.c:1289:15
    #5 0x638127 in lyd_parse_json /home/ci/src/cesnet-gerrit-public/github/CESNET/libyang/src/parser_json.c:1500:14
    #6 0x5a5f93 in lyd_parse /home/ci/src/cesnet-gerrit-public/github/CESNET/libyang/src/tree_data.c:363:14
    #7 0x5a6c82 in lyd_parse_data /home/ci/src/cesnet-gerrit-public/github/CESNET/libyang/src/tree_data.c:435:12
    #8 0x5a6df3 in lyd_parse_data_mem /home/ci/src/cesnet-gerrit-public/github/CESNET/libyang/src/tree_data.c:446:11
    #9 0xc453b7 in test_leaf /home/ci/src/cesnet-gerrit-public/github/CESNET/libyang/tests/utests/data/test_parser_json.c:123:5
    #10 0x7fc9c5ed6cb0  (/lib64/libcmocka.so.0+0x5cb0)
    #11 0x7fc9c5ed738a in _cmocka_run_group_tests (/lib64/libcmocka.so.0+0x638a)
    #12 0xc3c1c1 in main /home/ci/src/cesnet-gerrit-public/github/CESNET/libyang/tests/utests/data/test_parser_json.c:595:12
    #13 0x7fc9c5afeb74 in __libc_start_main /usr/src/debug/glibc-2.33/csu/../csu/libc-start.c:332:16
    #14 0x42164d in _start (/home/ci/build/github/CESNET/libyang/tests/utest_parser_json+0x42164d)
```

**Comment by michalvasko** [comment]
Fine, fixed.

**Comment by syyyr** [comment]
It seems that UB is fixed for now. Thanks!
