### ISSUE TITLE
Segmentation fault in lyd_parse_opaq_error

### ISSUE THREAD

**Issue by ddomingos-daitan** [CESNET/libyang#1798]
Hi, it seems that a recent code added in the following commit started causing a segfault in one of our tests
commit: https://github.com/CESNET/libyang/commit/bfff6ac1a62078599944b4d2dc08ba6b1bae9052

I've isolated the test in a simple way to be easily reproduced. The simplest model is:

```
module test-identityref {
  namespace "http://example.com/test-id-ref";
  prefix "test-id-ref";

  identity base-id;

  identity derived-id {
    base base-id;
  }

  container test-container {
    leaf test-leaf {
      type identityref {
        base base-id;
      }
    }
  }
}
```
And the input:
```
<test-container xmlns="http://example.com/test-id-ref">
  <test-leaf>base-id</test-leaf>
</test-container>
```

If I use "derived-id" it works fine and if I use a commit prior then the one specified, I get the generic error:
"Opaque (invalid) node "test-leaf" cannot be created"

The backtrace is:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f8424a684d1 in lyxml_ns_get (ns_set=0x0, prefix=0x0, prefix_len=0) at /home/ddomingos/libyang/src/xml.c:210
210	    for (uint32_t u = ns_set->count - 1; u + 1 > 0; --u) {
[Current thread is 1 (Thread 0x7f8422a92700 (LWP 12651))]
(gdb) bt
#0  0x00007f8424a684d1 in lyxml_ns_get (ns_set=0x0, prefix=0x0, prefix_len=0) at /home/ddomingos/libyang/src/xml.c:210
#1  0x00007f8424a61f55 in ly_xml_resolve_prefix (ctx=0x55af7d41ad60, prefix=0x0, prefix_len=0, prefix_data=0x0) at /home/ddomingos/libyang/src/plugins_types.c:99
#2  0x00007f8424a6220c in lyplg_type_identity_module (ctx=0x55af7d41ad60, ctx_node=0x55af7d585a40, prefix=0x55af7d526ce0 "base-id", prefix_len=0, format=LY_VALUE_XML, prefix_data=0x0)
    at /home/ddomingos/libyang/src/plugins_types.c:172
#3  0x00007f8424a8e50d in identityref_str2ident (value=0x55af7d526ce0 "base-id", value_len=7, format=LY_VALUE_XML, prefix_data=0x0, ctx=0x55af7d41ad60, ctx_node=0x55af7d585a40, ident=0x7f8422a915c8, 
    err=0x7f8422a91660) at /home/ddomingos/libyang/src/plugins_types/identityref.c:103
#4  0x00007f8424a8ead6 in lyplg_type_store_identityref (ctx=0x55af7d41ad60, type=0x55af7d5310a0, value=0x55af7d526ce0, value_len=7, options=0, format=LY_VALUE_XML, prefix_data=0x0, hints=511, 
    ctx_node=0x55af7d585a40, storage=0x7f8422a91670, unres=0x0, err=0x7f8422a91660) at /home/ddomingos/libyang/src/plugins_types/identityref.c:241
#5  0x00007f84249a5d18 in lys_value_validate (ctx=0x55af7d41ad60, node=0x55af7d585a40, value=0x55af7d526ce0 "base-id", value_len=7, format=LY_VALUE_XML, prefix_data=0x0)
    at /home/ddomingos/libyang/src/tree_data.c:136
#6  0x00007f84249b98d3 in lyd_parse_opaq_error (node=0x7f840c001fe0) at /home/ddomingos/libyang/src/tree_data_helpers.c:568
#7  0x00007f842472f728 in sr_edit_apply_create (first_node=0x7f840c006bf8, parent_node=0x7f840c006bc0, match_node=0x7f8422a91800, val_equal=0, edit_node=0x7f840c001fe0, diff_parent=0x7f840c002610, 
    diff_root=0x7f8422a91990, diff_node=0x7f8422a91810, next_op=0x7f8422a917e8, change=0x7f8422a919e4) at /home/ddomingos/sysrepo/src/edit_diff.c:2216
#8  0x00007f842472ff8b in sr_edit_apply_r (first_node=0x7f840c006bf8, parent_node=0x7f840c006bc0, edit_node=0x7f840c001fe0, parent_op=EDIT_MERGE, diff_parent=0x7f840c002610, diff_root=0x7f8422a91990, 
    oper_edit=0, flags=0, change=0x7f8422a919e4) at /home/ddomingos/sysrepo/src/edit_diff.c:2415
#9  0x00007f84247304e3 in sr_edit_apply_r (first_node=0x7f8422a91a90, parent_node=0x0, edit_node=0x7f840c001f90, parent_op=EDIT_CONTINUE, diff_parent=0x7f840c002610, diff_root=0x7f8422a91990, 
    oper_edit=0, flags=0, change=0x7f8422a919e4) at /home/ddomingos/sysrepo/src/edit_diff.c:2529
#10 0x00007f84247306a7 in sr_edit_mod_apply (edit=0x7f840c001f90, ly_mod=0x55af7d527320, oper_edit=0, data=0x7f8422a91a90, diff=0x7f8422a91a88, change=0x7f8422a919e4)
    at /home/ddomingos/sysrepo/src/edit_diff.c:2574
#11 0x00007f8424723356 in sr_modinfo_edit_apply (mod_info=0x7f8422a91a80, edit=0x7f840c001f90, create_diff=1) at /home/ddomingos/sysrepo/src/modinfo.c:388
#12 0x00007f8424709720 in sr_apply_changes (session=0x7f8410027800, timeout_ms=180000) at /home/ddomingos/sysrepo/src/sysrepo.c:3400
#13 0x000055af7c91fa52 in np2srv_rpc_editconfig_cb (session=0x7f840c028bf0, UNUSED_sub_id=59, UNUSED_op_path=0x55af7d574a10 "/ietf-netconf:edit-config", input=0x7f840c024210, event=SR_EV_RPC, 
    UNUSED_request_id=1, UNUSED_output=0x7f840c0014f0, UNUSED_private_data=0x0) at /home/ddomingos/netopeer2/src/netconf.c:411
#14 0x00007f842474bfb3 in sr_shmsub_rpc_listen_call_callback (rpc_sub=0x55af7d537530, ev_sess=0x7f840c028bf0, input_op=0x7f840c024210, event=SR_SUB_EV_RPC, request_id=1, output_op=0x7f8422a91cb0, 
    err_code=0x7f8422a91c78) at /home/ddomingos/sysrepo/src/shm_sub.c:2993
#15 0x00007f842474cd02 in sr_shmsub_rpc_listen_process_rpc_events (rpc_subs=0x55af7d5948b0, conn=0x55af7d405bc0) at /home/ddomingos/sysrepo/src/shm_sub.c:3278
#16 0x00007f842470b13c in sr_subscription_process_events (subscription=0x55af7d553590, session=0x0, stop_time_in=0x7f8422a91e10) at /home/ddomingos/sysrepo/src/sysrepo.c:4011
#17 0x00007f842474dce4 in sr_shmsub_listen_thread (arg=0x55af7d553590) at /home/ddomingos/sysrepo/src/shm_sub.c:3671
#18 0x00007f8424ce16db in start_thread (arg=0x7f8422a92700) at pthread_create.c:463
#19 0x00007f842442971f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

I don't have full understanding of the code to propose a fix but it seems the problem is that in the new function lyd_parse_opaq_error  it is converting the input node to the opaque structure and then passing opaq->val_prefix_data to lys_value_validate. This value is null and goes all the way to lyxml_ns_get which tries to access some field on it thus generating the segfault.
I'd appreciate help on this. Thanks

**Comment by michalvasko** [comment]
Quite a complex use-case revealing several problems that should now all be fixed.

**Comment by ddomingos-daitan** [comment]
I can confirm it is now fixed and with a more specific error response:
`Invalid identityref "base-id" value - identity not derived from the base "test-identityref:base-id"`
Thanks for the quick fix
