### ISSUE TITLE
Edit-config with invalid config data causes SIGSEGV

### ISSUE THREAD

**Issue by pfeige** [CESNET/libyang#1816]
Hi,

we have a couple of edit-config testcases with invalid config data to verify the stability and responses of the stack. The following two RPCs cause a SIGSEGV in parser_xml.c:
~~~
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1644ae25-4d5f-434f-8a64-ef37beb14e5c">
  <edit-config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
    <target>
      <running/>
    </target>
    <config>
      <delete-config>
        <aaa>
          <bbb>BBB</bbb>
          <ccc>CCC</ccc>
        </aaa>
      </delete-config>
    </config>
  </edit-config>
</rpc>

<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="5a515849-73c2-4acd-a098-7bd8560b4a33">
  <edit-config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
    <target>
      <running/>
    </target>
    <config>
      <kill-session>
        <aaa>
          <bbb>BBB</bbb>
          <ccc>CCC</ccc>
        </aaa>
      </kill-session>
    </config>
  </edit-config>
</rpc>
~~~
Here is the corresponding stack trace:
~~~
Core was generated by `/bin/netopeer2-server -v 4 -d'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
[Current thread is 1 (Thread 0x7f56ff63b700 (LWP 4237))]
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007f5702b16968 in lydxml_nested_ext (lydctx=0x7f56f8001640, parent=0x7f56f80031f0) at /root/package/install/resources/libyang/build/src/parser_xml.c:452
#2  0x00007f5702b16ffe in lydxml_subtree_r (lydctx=0x7f56f8001640, parent=0x7f56f80031f0, first_p=0x7f56f8003228, parsed=0x0)
    at /root/package/install/resources/libyang/build/src/parser_xml.c:578
#3  0x00007f5702b1792f in lydxml_subtree_r (lydctx=0x7f56f8001640, parent=0x0, first_p=0x7f56ff63a920, parsed=0x0)
    at /root/package/install/resources/libyang/build/src/parser_xml.c:720
#4  0x00007f5702b17cb7 in lydxml_subtree_r (lydctx=0x7f56f8001640, parent=0x7f56f8002e40, first_p=0x7f56f8002e78, parsed=0x0)
    at /root/package/install/resources/libyang/build/src/parser_xml.c:778
#5  0x00007f5702b1792f in lydxml_subtree_r (lydctx=0x7f56f8001640, parent=0x0, first_p=0x7f56ff63abe0, parsed=0x7f56ff63abf0)
    at /root/package/install/resources/libyang/build/src/parser_xml.c:720
#6  0x00007f5702b19c51 in lyd_parse_xml (ctx=0x55ef1292c6e0, ext=0x0, parent=0x0, first_p=0x7f56ff63abe0, in=0x7f56f80015d0, parse_opts=327680, val_opts=0, 
    data_type=LYD_TYPE_RPC_NETCONF, envp=0x7f56ff63abe8, parsed=0x7f56ff63abf0, subtree_sibling=0x0, lydctx_p=0x7f56ff63abd8)
    at /root/package/install/resources/libyang/build/src/parser_xml.c:1544
#7  0x00007f5702b00436 in lyd_parse_op_ (ctx=0x55ef1292c6e0, ext=0x0, parent=0x0, in=0x7f56f80015d0, format=LYD_XML, data_type=LYD_TYPE_RPC_NETCONF, tree=0x7f56f8001620, 
    op=0x7f56f8001628) at /root/package/install/resources/libyang/build/src/tree_data.c:567
#8  0x00007f5702b007b2 in lyd_parse_op (ctx=0x55ef1292c6e0, parent=0x0, in=0x7f56f80015d0, format=LYD_XML, data_type=LYD_TYPE_RPC_NETCONF, tree=0x7f56f8001620, 
    op=0x7f56f8001628) at /root/package/install/resources/libyang/build/src/tree_data.c:634
#9  0x00007f57032e152d in nc_server_recv_rpc_io (session=0x55ef12a44620, io_timeout=10, rpc=0x7f56ff63ad18)
    at /root/package/install/resources/libnetconf2/build/src/session_server.c:1347
#10 0x00007f57032e272a in nc_ps_poll (ps=0x55ef129ae070, timeout=10, session=0x7f56ff63ae90) at /root/package/install/resources/libnetconf2/build/src/session_server.c:1804
#11 0x000055ef1080c00d in worker_thread (arg=0x55ef12a00e80) at /root/package/resources/build/src/main.c:1003
#12 0x00007f5702e3a6db in ?? ()
#13 0x0000000000000000 in ?? ()
(gdb)
~~~
It seems that the ext_parse_cb in these cases is NULL.

BR,
Peter

**Comment by michalvasko** [comment]
Right, missing check for that, fixed.
