### ISSUE TITLE
Problem with parsing of yang module

### ISSUE THREAD

**Issue by lukasmacko** [CESNET/libyang#183]
Based on https://github.com/sysrepo/sysrepo/issues/451
I've created a tiny program that tries to parse a yang model however it crashes.

```C
#include <stdio.h>
#include <stdlib.h>
#include <libyang/libyang.h>

int main(int argc, char **argv)
{
  struct ly_ctx *ctx = ly_ctx_new("/home/lukas/playground/yang/standard/ietf/RFC");
  ly_ctx_load_module(ctx, "bbf-fast", NULL);
  ly_ctx_destroy(ctx, NULL);
}
```
Yang models needed:
- [broadBand](https://github.com/BroadbandForum/yang/tree/master/standard) model that the program is trying to load is under interface directory
- [ietf-models](https://github.com/YangModels/yang/tree/master/standard/ietf/RFC)

```
libyang[0]: Invalid keyword "�".
libyang[0]: Submodule parsing failed.
libyang[0]: Including "bbf-fast-line-status-body" module into "bbf-fast" failed.
libyang[0]: Submodule "bbf-fast-read-test-body" parsing failed.
libyang[0]: Including "bbf-fast-read-test-body" module into "bbf-fast" failed.
libyang[0]: Submodule "bbf-fast-test-diagnostics" parsing failed.
libyang[0]: Including "bbf-fast-test-diagnostics" module into "bbf-fast" failed.
libyang[0]: Module "bbf-fast" parsing failed.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b11162 in lydict_remove (ctx=0x63e3d0, value=0x64f350 "line") at /home/lukas/playground/libyang/src/dict.c:135
135	    while (record && record->value != value) {
(gdb) bt
#0  0x00007ffff7b11162 in lydict_remove (ctx=0x63e3d0, value=0x64f350 "line") at /home/lukas/playground/libyang/src/dict.c:135
#1  0x00007ffff7b6ebe1 in lys_node_free (node=0x628e40, private_destructor=0x0, shallow=0) at /home/lukas/playground/libyang/src/tree_schema.c:1840
#2  0x00007ffff7b6ec76 in lys_node_free (node=0x64f370, private_destructor=0x0, shallow=0) at /home/lukas/playground/libyang/src/tree_schema.c:1849
#3  0x00007ffff7b6ec76 in lys_node_free (node=0x60aed0, private_destructor=0x0, shallow=0) at /home/lukas/playground/libyang/src/tree_schema.c:1849
#4  0x00007ffff7b6ec76 in lys_node_free (node=0x613b00, private_destructor=0x0, shallow=0) at /home/lukas/playground/libyang/src/tree_schema.c:1849
#5  0x00007ffff7b6f434 in module_free_common (module=0x60efb0, private_destructor=0x0) at /home/lukas/playground/libyang/src/tree_schema.c:2004
#6  0x00007ffff7b71696 in lys_free (module=0x60efb0, private_destructor=0x0, remove_from_ctx=0) at /home/lukas/playground/libyang/src/tree_schema.c:2586
#7  0x00007ffff7b0e585 in ly_ctx_destroy (ctx=0x602010, private_destructor=0x0) at /home/lukas/playground/libyang/src/context.c:179
#8  0x000000000040077a in main ()
```

**Comment by lukasmacko** [comment]
sorry, this is probably fixed in devel by https://github.com/CESNET/libyang/issues/160
