### ISSUE TITLE
SIGSEGV for empty namespace in subtree filter

### ISSUE THREAD

**Issue by pfeige** [CESNET/libyang#1870]
A get-config with a subtree filter where the namespace is empty leads to a SIGSEGV in printer_xml.c xml_print_ns().
~~~
<filter><whatever xmlns=""/></filter>
~~~
The parameter ns is NULL and therefore the strcmp() crashes.
~~~
Core was generated by `netopeer2-server -d -t 600 -v 2'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:32
32	../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.
[Current thread is 1 (Thread 0x7fafb9ffb700 (LWP 3436))]
(gdb) bt
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:32
#1  0x00007fafc60a9e77 in xml_print_ns (pctx=0x7fafb9ffabc0, ns=0x0, new_prefix=0x0, prefix_opts=2)
    at /root/package/install/generic/resources/libyang/build/src/printer_xml.c:74
#2  0x00007fafc60aa0bb in xml_print_ns_opaq (pctx=0x7fafb9ffabc0, format=LY_VALUE_XML, name=0x7fafa8002bd0, prefix_opts=2)
    at /root/package/install/generic/resources/libyang/build/src/printer_xml.c:116
#3  0x00007fafc60aa88d in xml_print_opaq_open (pctx=0x7fafb9ffabc0, node=0x7fafa8002b90) at /root/package/install/generic/resources/libyang/build/src/printer_xml.c:293
#4  0x00007fafc60ab0b0 in xml_print_opaq (pctx=0x7fafb9ffabc0, node=0x7fafa8002b90) at /root/package/install/generic/resources/libyang/build/src/printer_xml.c:472
#5  0x00007fafc60ab37c in xml_print_node (pctx=0x7fafb9ffabc0, node=0x7fafa8002b90) at /root/package/install/generic/resources/libyang/build/src/printer_xml.c:530
#6  0x00007fafc60aae98 in xml_print_anydata (pctx=0x7fafb9ffabc0, node=0x7fafa8002c20) at /root/package/install/generic/resources/libyang/build/src/printer_xml.c:425
#7  0x00007fafc60ab41f in xml_print_node (pctx=0x7fafb9ffabc0, node=0x7fafa8002c20) at /root/package/install/generic/resources/libyang/build/src/printer_xml.c:546
#8  0x00007fafc60aabe3 in xml_print_inner (pctx=0x7fafb9ffabc0, node=0x7fafa8002990) at /root/package/install/generic/resources/libyang/build/src/printer_xml.c:374
#9  0x00007fafc60ab3ef in xml_print_node (pctx=0x7fafb9ffabc0, node=0x7fafa8002990) at /root/package/install/generic/resources/libyang/build/src/printer_xml.c:538
#10 0x00007fafc60ab5d8 in xml_print_data (out=0x7fafa8001490, root=0x7fafa8002990, options=3) at /root/package/install/generic/resources/libyang/build/src/printer_xml.c:585
#11 0x00007fafc60a973d in lyd_print_ (out=0x7fafa8001490, root=0x7fafa8002990, format=LYD_XML, options=3)
    at /root/package/install/generic/resources/libyang/build/src/printer_data.c:33
#12 0x00007fafc60a9a6c in lyd_print_mem (strp=0x7fafb9ffacd8, root=0x7fafa8002990, format=LYD_XML, options=3)
    at /root/package/install/generic/resources/libyang/build/src/printer_data.c:100
#13 0x00007fafc6868b7f in nc_ps_poll (ps=0x55d600698470, timeout=10, session=0x7fafb9ffae50)
    at /root/package/install/generic/resources/libnetconf2/build/src/session_server.c:1808
#14 0x000055d5fe80ce92 in worker_thread (arg=0x55d6006a9c70) at /root/package/install/generic/resources/netopeer2/build/src/main.c:1041
#15 0x00007fafc63c06db in start_thread (arg=0x7fafb9ffb700) at pthread_create.c:463
#16 0x00007fafc48b161f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

~~~

**Comment by pfeige** [comment]
This is in our additional code for snippet logging.
