### ISSUE TITLE
`lys_compile_iffeature`: Memory leaks via `regress_fuzz_lys_parse_mem`

### ISSUE THREAD

**Issue by jktjkt** [CESNET/libyang#1976]
Looks like there are two memleaks, they are also reproducible via e.g. `yanglint tests/fuzz/corpus/lys_parse_mem/issue723.yang`:
```
Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x4cfc07 in __interceptor_calloc (/home/jkt/work/prog/_build/czechlight-clang14-asan-ubsan-ly2/libyang/tests/fuzz/lys_parse_mem/regress_fuzz_lys_parse_mem+0x4cfc07)
    #1 0x7f02aa21e364 in lys_compile_iffeature libyang/src/schema_features.c:411:5
    #2 0x7f02aa21c4e6 in lys_eval_iffeatures libyang/src/schema_features.c:521:9
    #3 0x7f02aa1c9783 in lys_compile_node_ libyang/src/schema_compile_node.c:2623:5
    #4 0x7f02aa1aee84 in lys_compile_node libyang/src/schema_compile_node.c:4213:11
    #5 0x7f02aa1bd8f4 in lys_compile_node_list libyang/src/schema_compile_node.c:3301:9
    #6 0x7f02aa1c9c98 in lys_compile_node_ libyang/src/schema_compile_node.c:2656:5
    #7 0x7f02aa1aee84 in lys_compile_node libyang/src/schema_compile_node.c:4213:11
    #8 0x7f02aa160016 in lys_compile libyang/src/schema_compile.c:1580:9
    #9 0x7f02aa16494f in lys_compile_depset_r libyang/src/schema_compile.c:1386:9
    #10 0x7f02aa164497 in lys_compile_depset_all libyang/src/schema_compile.c:1445:9
    #11 0x7f02aa244a67 in lys_parse libyang/src/tree_schema.c:1925:9
    #12 0x7f02aa244dde in lys_parse_mem libyang/src/tree_schema.c:1951:11
    #13 0x513183 in LLVMFuzzerTestOneInput libyang/tests/fuzz/lys_parse_mem.c:33:5
    #14 0x5133e4 in main libyang/tests/fuzz/main.c:42:5
    #15 0x7f02a982924d in __libc_start_call_main (/nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libc.so.6+0x2924d) (BuildId: 3d6884d200ead572b7b89a4133f645c7a3c039ed)
    #16 0x7f02a9829308 in __libc_start_main@GLIBC_2.2.5 (/nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libc.so.6+0x29308) (BuildId: 3d6884d200ead572b7b89a4133f645c7a3c039ed)
    #17 0x41f394 in _start (/home/jkt/work/prog/_build/czechlight-clang14-asan-ubsan-ly2/libyang/tests/fuzz/lys_parse_mem/regress_fuzz_lys_parse_mem+0x41f394)

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x4cfc07 in __interceptor_calloc (/home/jkt/work/prog/_build/czechlight-clang14-asan-ubsan-ly2/libyang/tests/fuzz/lys_parse_mem/regress_fuzz_lys_parse_mem+0x4cfc07)
    #1 0x7f02aa21e4d8 in lys_compile_iffeature libyang/src/schema_features.c:412:17
    #2 0x7f02aa21c4e6 in lys_eval_iffeatures libyang/src/schema_features.c:521:9
    #3 0x7f02aa1c9783 in lys_compile_node_ libyang/src/schema_compile_node.c:2623:5
    #4 0x7f02aa1aee84 in lys_compile_node libyang/src/schema_compile_node.c:4213:11
    #5 0x7f02aa1bd8f4 in lys_compile_node_list libyang/src/schema_compile_node.c:3301:9
    #6 0x7f02aa1c9c98 in lys_compile_node_ libyang/src/schema_compile_node.c:2656:5
    #7 0x7f02aa1aee84 in lys_compile_node libyang/src/schema_compile_node.c:4213:11
    #8 0x7f02aa160016 in lys_compile libyang/src/schema_compile.c:1580:9
    #9 0x7f02aa16494f in lys_compile_depset_r libyang/src/schema_compile.c:1386:9
    #10 0x7f02aa164497 in lys_compile_depset_all libyang/src/schema_compile.c:1445:9
    #11 0x7f02aa244a67 in lys_parse libyang/src/tree_schema.c:1925:9
    #12 0x7f02aa244dde in lys_parse_mem libyang/src/tree_schema.c:1951:11
    #13 0x513183 in LLVMFuzzerTestOneInput libyang/tests/fuzz/lys_parse_mem.c:33:5
    #14 0x5133e4 in main libyang/tests/fuzz/main.c:42:5
    #15 0x7f02a982924d in __libc_start_call_main (/nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libc.so.6+0x2924d) (BuildId: 3d6884d200ead572b7b89a4133f645c7a3c039ed)
    #16 0x7f02a9829308 in __libc_start_main@GLIBC_2.2.5 (/nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libc.so.6+0x29308) (BuildId: 3d6884d200ead572b7b89a4133f645c7a3c039ed)
    #17 0x41f394 in _start (/home/jkt/work/prog/_build/czechlight-clang14-asan-ubsan-ly2/libyang/tests/fuzz/lys_parse_mem/regress_fuzz_lys_parse_mem+0x41f394)

SUMMARY: AddressSanitizer: 17 byte(s) leaked in 2 allocation(s).
test regress_fuzz_lys_parse_mem - issue723.yang successful
```
and:
```
Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x4cfc07 in __interceptor_calloc (/home/jkt/work/prog/_build/czechlight-clang14-asan-ubsan-ly2/libyang/tests/fuzz/lys_parse_mem/regress_fuzz_lys_parse_mem+0x4cfc07)
    #1 0x7f447ec1e364 in lys_compile_iffeature libyang/src/schema_features.c:411:5
    #2 0x7f447ec1c4e6 in lys_eval_iffeatures libyang/src/schema_features.c:521:9
    #3 0x7f447ebc9783 in lys_compile_node_ libyang/src/schema_compile_node.c:2623:5
    #4 0x7f447ebaee84 in lys_compile_node libyang/src/schema_compile_node.c:4213:11
    #5 0x7f447eb60016 in lys_compile libyang/src/schema_compile.c:1580:9
    #6 0x7f447eb6494f in lys_compile_depset_r libyang/src/schema_compile.c:1386:9
    #7 0x7f447eb64497 in lys_compile_depset_all libyang/src/schema_compile.c:1445:9
    #8 0x7f447ec44a67 in lys_parse libyang/src/tree_schema.c:1925:9
    #9 0x7f447ec44dde in lys_parse_mem libyang/src/tree_schema.c:1951:11
    #10 0x513183 in LLVMFuzzerTestOneInput libyang/tests/fuzz/lys_parse_mem.c:33:5
    #11 0x5133e4 in main libyang/tests/fuzz/main.c:42:5
    #12 0x7f447e22924d in __libc_start_call_main (/nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libc.so.6+0x2924d) (BuildId: 3d6884d200ead572b7b89a4133f645c7a3c039ed)
    #13 0x7f447e229308 in __libc_start_main@GLIBC_2.2.5 (/nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libc.so.6+0x29308) (BuildId: 3d6884d200ead572b7b89a4133f645c7a3c039ed)
    #14 0x41f394 in _start (/home/jkt/work/prog/_build/czechlight-clang14-asan-ubsan-ly2/libyang/tests/fuzz/lys_parse_mem/regress_fuzz_lys_parse_mem+0x41f394)

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x4cfc07 in __interceptor_calloc (/home/jkt/work/prog/_build/czechlight-clang14-asan-ubsan-ly2/libyang/tests/fuzz/lys_parse_mem/regress_fuzz_lys_parse_mem+0x4cfc07)
    #1 0x7f447ec1e4d8 in lys_compile_iffeature libyang/src/schema_features.c:412:17
    #2 0x7f447ec1c4e6 in lys_eval_iffeatures libyang/src/schema_features.c:521:9
    #3 0x7f447ebc9783 in lys_compile_node_ libyang/src/schema_compile_node.c:2623:5
    #4 0x7f447ebaee84 in lys_compile_node libyang/src/schema_compile_node.c:4213:11
    #5 0x7f447eb60016 in lys_compile libyang/src/schema_compile.c:1580:9
    #6 0x7f447eb6494f in lys_compile_depset_r libyang/src/schema_compile.c:1386:9
    #7 0x7f447eb64497 in lys_compile_depset_all libyang/src/schema_compile.c:1445:9
    #8 0x7f447ec44a67 in lys_parse libyang/src/tree_schema.c:1925:9
    #9 0x7f447ec44dde in lys_parse_mem libyang/src/tree_schema.c:1951:11
    #10 0x513183 in LLVMFuzzerTestOneInput libyang/tests/fuzz/lys_parse_mem.c:33:5
    #11 0x5133e4 in main libyang/tests/fuzz/main.c:42:5
    #12 0x7f447e22924d in __libc_start_call_main (/nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libc.so.6+0x2924d) (BuildId: 3d6884d200ead572b7b89a4133f645c7a3c039ed)
    #13 0x7f447e229308 in __libc_start_main@GLIBC_2.2.5 (/nix/store/9xfad3b5z4y00mzmk2wnn4900q0qmxns-glibc-2.35-224/lib/libc.so.6+0x29308) (BuildId: 3d6884d200ead572b7b89a4133f645c7a3c039ed)
    #14 0x41f394 in _start (/home/jkt/work/prog/_build/czechlight-clang14-asan-ubsan-ly2/libyang/tests/fuzz/lys_parse_mem/regress_fuzz_lys_parse_mem+0x41f394)

SUMMARY: AddressSanitizer: 17 byte(s) leaked in 2 allocation(s).
test regress_fuzz_lys_parse_mem - issue735.yang successful
```

**Comment by michalvasko** [comment]
Right, fixed.
