### ISSUE TITLE
SIGSEGV in lyd_find_sibling_first when target is opaq list node

### ISSUE THREAD

**Issue by q664742232** [CESNET/libyang#2044]
module
```
typedef STRING {
        type string {
            length "0..31";
        }
    }

    typedef ENUM {
        type enumeration {
            enum zero;
            enum one;
            enum seven {
                value 7;
            }
        }
    }


    /*
     * Be used in edit-config
     */
    container A {
        list B {
            key "b1";
            leaf b1 {type STRING;}
            leaf b2 {type int32;}
            leaf b3 {type boolean;}
            leaf b4 {type ENUM;}
        }
    }
```

edit-config
```
<?xml version="1.0" encoding="UTF8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2" pid="4115019776">
  <edit-config>
    <target>
      <running/>
    </target>
    <config xmlns:ext="urn:huawei:yang:huawei-mo-extensions" ext:config-trans-no="124">
      <A xmlns="test:test-rfc6241" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
        <B>
          <bb>b2</bb>
        </B>
      </A>
    </config>
  </edit-config>
</rpc>
```

callstack
```
#0  0x00007ffff5f435ba in ?? () from /usr/lib64/libc.so.6
#1  0x00007ffff61569c3 in lyd_compare_single_value (node1=0x7fffa4004250, node2=0x7fffa40020a0) at /root/codes/opensource/libyang/src/tree_data.c:1263
#2  0x00007ffff6156bb9 in lyd_compare_single_ (node1=0x7fffa4004250, node2=0x7fffa40020a0, options=4, parental_schemas_checked=0 '\000') at /root/codes/opensource/libyang/src/tree_data.c:1329
#3  0x00007ffff61570b9 in lyd_compare_single (node1=0x7fffa4004250, node2=0x7fffa40020a0, options=4) at /root/codes/opensource/libyang/src/tree_data.c:1447
#4  0x00007ffff615ae22 in lyd_find_sibling_first (siblings=0x7fffa4004250, target=0x7fffa40020a0, match=0x7fffc808c670) at /root/codes/opensource/libyang/src/tree_data.c:2599
```

version master，and v2.0.231 seems ok

detal
```
(gdb) f 1
#1  0x00007ffff61569c3 in lyd_compare_single_value (node1=0x7fffa4004250, node2=0x7fffa40020a0) at /root/codes/opensource/libyang/src/tree_data.c:1263
1263	    if (strcmp(val1, val2)) {
(gdb) list
1258	    } else {
1259	        val2 = lyd_get_value(node2);
1260	    }
1261	
1262	    /* compare values */
1263	    if (strcmp(val1, val2)) {
1264	        rc = LY_ENOT;
1265	    }
1266	
1267	    free(val_dyn);
(gdb) list -
1248	        if (!mod) {
1249	            return LY_ENOT;
1250	        }
1251	
1252	        assert(!val_dyn);
1253	        if (asprintf(&val_dyn, "%s%s", mod->name, col) == -1) {
1254	            LOGMEM(LYD_CTX(node2));
1255	            return LY_EMEM;
1256	        }
1257	        val2 = val_dyn;
(gdb) list -
1238	        if (asprintf(&val_dyn, "%s%s", mod->name, col) == -1) {
1239	            LOGMEM(LYD_CTX(node1));
1240	            return LY_EMEM;
1241	        }
1242	        val1 = val_dyn;
1243	    } else {
1244	        val1 = lyd_get_value(node1);
1245	    }
1246	    if (opaq2 && ((opaq2->format == LY_VALUE_XML) || (opaq2->format == LY_VALUE_STR_NS)) && (col = strchr(opaq2->value, ':'))) {
1247	        mod = ly_resolve_prefix(LYD_CTX(node2), opaq2->value, col - opaq2->value, opaq2->format, opaq2->val_prefix_data);
(gdb) p val1
$11 = 0x0
(gdb) p val2
$12 = 0x7fffb8002820 ""
(gdb) p opaq2
$13 = (const struct lyd_node_opaq *) 0x7fffa40020a0
(gdb) p *opaq2
$14 = {{node = {hash = 0, flags = 0, schema = 0x0, parent = 0x7fffa4002000, next = 0x0, prev = 0x7fffa40020a0, meta = 0x0, priv = 0x0}, {hash = 0, flags = 0, schema = 0x0, parent = 0x7fffa4002000, next = 0x0, prev = 0x7fffa40020a0, meta = 0x0, priv = 0x0}}, 
  child = 0x7fffa4004e30, name = {name = 0x7fffb8003290 "B", prefix = 0x0, {module_ns = 0x7fffb8208490 "test:test-rfc6241", module_name = 0x7fffb8208490 "test:test-rfc6241"}}, value = 0x7fffb8002820 "", hints = 64, format = LY_VALUE_XML, val_prefix_data = 0x0, 
  attr = 0x0, ctx = 0x7fffb8001450}
(gdb) p col
$15 = 0x0
(gdb) p mod
$16 = (const struct lys_module *) 0x7ffff615fa56 <lyd_node_schema+257>
(gdb) list -
1228	
1229	    /* get their values */
1230	    if (opaq1 && ((opaq1->format == LY_VALUE_XML) || (opaq1->format == LY_VALUE_STR_NS)) && (col = strchr(opaq1->value, ':'))) {
1231	        /* XML value with a prefix, try to transform it into a JSON (canonical) value */
1232	        mod = ly_resolve_prefix(LYD_CTX(node1), opaq1->value, col - opaq1->value, opaq1->format, opaq1->val_prefix_data);
1233	        if (!mod) {
1234	            /* unable to compare */
1235	            return LY_ENOT;
1236	        }
1237	
(gdb) p opaq 1
No symbol "opaq" in current context.
(gdb) p opaq1
$17 = (const struct lyd_node_opaq *) 0x0
(gdb) p *node1
$18 = {hash = 1565496840, flags = 4, schema = 0x7fffb82109c0, parent = 0x7fffa4004200, next = 0x0, prev = 0x7fffa4004250, meta = 0x0, priv = 0x0}
(gdb) p *node 2
No symbol "node" in current context.
(gdb) p *node2
$19 = {hash = 0, flags = 0, schema = 0x0, parent = 0x7fffa4002000, next = 0x0, prev = 0x7fffa40020a0, meta = 0x0, priv = 0x0}
(gdb) p *node1.schema 
$20 = {nodetype = 16, flags = 133, hash = "\000\000\000", module = 0x7fffb820d660, parent = 0x7fffb8210940, next = 0x0, prev = 0x7fffb82109c0, name = 0x7fffb8003290 "B", dsc = 0x0, ref = 0x0, exts = 0x0, priv = 0x7fffc8322228}
(gdb) f 2
#2  0x00007ffff6156bb9 in lyd_compare_single_ (node1=0x7fffa4004250, node2=0x7fffa40020a0, options=4, parental_schemas_checked=0 '\000') at /root/codes/opensource/libyang/src/tree_data.c:1329
1329	        if ((r = lyd_compare_single_value(node1, node2))) {
```

**Comment by q664742232** [comment]
Oh I've just tried the latest libyang. It doesn't happen anymore. It's my fault. Thank you.
