### ISSUE TITLE
RESTCONF notifications: order of JSON keys matters

### ISSUE THREAD

**Issue by jktjkt** [CESNET/libyang#2080]
This one gets parsed successfully:
```json
{
  "ietf-restconf:notification" : {
    "eventTime" : "2013-12-21T00:01:00Z",
    "example-schema:event" : {
      "event-class" : "fault"
    }
  }
}
```
This one does not:
```json
{
  "ietf-restconf:notification" : {
    "example-schema:event" : {
      "event-class" : "fault"
    },
    "eventTime" : "2013-12-21T00:01:00Z"
  }
}
```
The log says:
```
libyang[0]: Unexpected object "event" instead of "eventTime". (path: Line number 4.)
```
The YANG model is trivial:
```yang
notification event {
    description "Example notification event.";
    leaf event-class {
        type string;
        description "Event class identifier.";
    }
}
```
Originally reported [here](https://github.com/CESNET/libyang-cpp/issues/14#issuecomment-1669969592), but with a weird prefix. That doesn't seem to matter.

**Comment by michalvasko** [comment]
Fixing this should be simple and I do not really have anything against it. The specs are not completely clear, but they do say the notification must [conform to an XML Schema](https://www.rfc-editor.org/rfc/rfc8040.html#section-6.4), which uses a [sequence](https://www.rfc-editor.org/rfc/rfc5277#section-4) for the elements so the order is strict. On the other hand, JSON is specified as not being ordered.

**Comment by safesintesi** [comment]
Messing around with notifications I would like to underline that this problem only appears to happen if the switch is between the notification metadata and the actual data, for example:

```JSON
{
    "ietf-restconf:notification" : {
        "module:event": {
            "priority": 1,
            "event-class": "fault"
        },
        "eventTime" : "2013-12-21T00:01:00Z"
    }
}
```
fails, but both
```JSON
{
    "ietf-restconf:notification" : {
        "eventTime" : "2013-12-21T00:01:00Z",
        "module:event": {
            "priority": 1,
            "event-class": "fault"
        }
    }
}
```
and
```JSON
{
    "ietf-restconf:notification" : {
        "eventTime" : "2013-12-21T00:01:00Z",
        "module:event": {
            "event-class": "fault",
            "priority": 1
        }
    }
}
```
succeed.

**Comment by michalvasko** [comment]
Yes, for standard YANG data the order is ignored. I have not made any changes because I have expected a reply and without it paid no more attention to this issue. So I am not sure it is still relevant, what I said before stands.

**Comment by jktjkt** [comment]
Yes, I think that the JSON parser should accept any order because of the well-known JSON properties. Furthermore, I think it can be argued that the XML parser should be made more relaxed as well, especially if the [`draft-ahuang-netconf-notif-yang`](https://datatracker.ietf.org/doc/html/draft-ahuang-netconf-notif-yang-02)  is accepted.

**Comment by michalvasko** [comment]
Fine, took me some time to figure out a fairly simple way of implementing this. I have modified it for XML as well but not sure if that draft is relevant here. Even if it got accepted, it is still just a "description" of how a notification is supposed to look like. Unless all new (and old) notifications are defined as augments to the structure in the draft (making `notification` statement useless), it will never be possible to parse notifications as YANG extension data.

**Comment by jktjkt** [comment]
Parsing this notification now leaks memory:
```json
{
  "ietf-restconf:notification" : {
    "eventTime" : "2013-12-21T00:01:00Z",
    "WTF:is-this" : {
    }
  }
}
```
Log:
```
==134172==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x555f4e5aca37 in __interceptor_calloc (/home/jkt/work/prog/_build/czechlight-clang16-asan-ubsan/libyang-cpp/test_data_node+0x195a37)
    #1 0x7f0d112c6016 in lyd_create_opaq github/CESNET/libyang/src/tree_data_new.c:439:12
    #2 0x7f0d112fe0f3 in lydjson_subtree_r github/CESNET/libyang/src/parser_json.c:1611:13
    #3 0x7f0d11306627 in lyd_parse_json_restconf github/CESNET/libyang/src/parser_json.c:2060:13
    #4 0x7f0d1126e0ea in lyd_parse_op_ github/CESNET/libyang/src/tree_data.c:351:18
    #5 0x7f0d1126d5d4 in lyd_parse_op github/CESNET/libyang/src/tree_data.c:430:12
    #6 0x7f0d11d1631d in libyang::Context::parseOp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, libyang::DataFormat, libyang::OperationType) const CzechLight/libyang-cpp/src/Context.cpp:204:20
    #7 0x555f4e645d65 in DOCTEST_ANON_FUNC_2()::$_45::operator()() const CzechLight/libyang-cpp/tests/data_node.cpp:1861:13
    #8 0x555f4e645d65 in DOCTEST_ANON_FUNC_2() CzechLight/libyang-cpp/tests/data_node.cpp:1861:13
    #9 0x555f4e6d1bd9 in doctest::Context::run() /home/jkt/work/prog/_build/czechlight-clang16-asan-ubsan/target/include/doctest/doctest.h:6727:21
    #10 0x555f4e6d7564 in main /home/jkt/work/prog/_build/czechlight-clang16-asan-ubsan/target/include/doctest/doctest.h:6805:71
    #11 0x7f0d10c3dacd in __libc_start_call_main (/nix/store/1x4ijm9r1a88qk7zcmbbfza324gx1aac-glibc-2.37-8/lib/libc.so.6+0x23acd) (BuildId: 344aaad51978b8c259311fba5dc7581f830bad5a)

Indirect leak of 21 byte(s) in 1 object(s) allocated from:
    #0 0x555f4e5ac6ef in malloc (/home/jkt/work/prog/_build/czechlight-clang16-asan-ubsan/libyang-cpp/test_data_node+0x1956ef)
    #1 0x7f0d112130ac in dict_insert github/CESNET/libyang/src/dict.c:203:28
    #2 0x7f0d11213754 in lydict_insert github/CESNET/libyang/src/dict.c:242:14
    #3 0x7f0d112c6200 in lyd_create_opaq github/CESNET/libyang/src/tree_data_new.c:455:9
    #4 0x7f0d112fe0f3 in lydjson_subtree_r github/CESNET/libyang/src/parser_json.c:1611:13
    #5 0x7f0d11306627 in lyd_parse_json_restconf github/CESNET/libyang/src/parser_json.c:2060:13
    #6 0x7f0d1126e0ea in lyd_parse_op_ github/CESNET/libyang/src/tree_data.c:351:18
    #7 0x7f0d1126d5d4 in lyd_parse_op github/CESNET/libyang/src/tree_data.c:430:12
    #8 0x7f0d11d1631d in libyang::Context::parseOp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, libyang::DataFormat, libyang::OperationType) const CzechLight/libyang-cpp/src/Context.cpp:204:20
    #9 0x555f4e645d65 in DOCTEST_ANON_FUNC_2()::$_45::operator()() const CzechLight/libyang-cpp/tests/data_node.cpp:1861:13
    #10 0x555f4e645d65 in DOCTEST_ANON_FUNC_2() CzechLight/libyang-cpp/tests/data_node.cpp:1861:13
    #11 0x555f4e6d1bd9 in doctest::Context::run() /home/jkt/work/prog/_build/czechlight-clang16-asan-ubsan/target/include/doctest/doctest.h:6727:21
    #12 0x555f4e6d7564 in main /home/jkt/work/prog/_build/czechlight-clang16-asan-ubsan/target/include/doctest/doctest.h:6805:71
    #13 0x7f0d10c3dacd in __libc_start_call_main (/nix/store/1x4ijm9r1a88qk7zcmbbfza324gx1aac-glibc-2.37-8/lib/libc.so.6+0x23acd) (BuildId: 344aaad51978b8c259311fba5dc7581f830bad5a)

Indirect leak of 10 byte(s) in 1 object(s) allocated from:
    #0 0x555f4e5ac6ef in malloc (/home/jkt/work/prog/_build/czechlight-clang16-asan-ubsan/libyang-cpp/test_data_node+0x1956ef)
    #1 0x7f0d112130ac in dict_insert github/CESNET/libyang/src/dict.c:203:28
    #2 0x7f0d11213754 in lydict_insert github/CESNET/libyang/src/dict.c:242:14
    #3 0x7f0d112c6076 in lyd_create_opaq github/CESNET/libyang/src/tree_data_new.c:443:5
    #4 0x7f0d112fe0f3 in lydjson_subtree_r github/CESNET/libyang/src/parser_json.c:1611:13
    #5 0x7f0d11306627 in lyd_parse_json_restconf github/CESNET/libyang/src/parser_json.c:2060:13
    #6 0x7f0d1126e0ea in lyd_parse_op_ github/CESNET/libyang/src/tree_data.c:351:18
    #7 0x7f0d1126d5d4 in lyd_parse_op github/CESNET/libyang/src/tree_data.c:430:12
    #8 0x7f0d11d1631d in libyang::Context::parseOp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, libyang::DataFormat, libyang::OperationType) const CzechLight/libyang-cpp/src/Context.cpp:204:20
    #9 0x555f4e645d65 in DOCTEST_ANON_FUNC_2()::$_45::operator()() const CzechLight/libyang-cpp/tests/data_node.cpp:1861:13
    #10 0x555f4e645d65 in DOCTEST_ANON_FUNC_2() CzechLight/libyang-cpp/tests/data_node.cpp:1861:13
    #11 0x555f4e6d1bd9 in doctest::Context::run() /home/jkt/work/prog/_build/czechlight-clang16-asan-ubsan/target/include/doctest/doctest.h:6727:21
    #12 0x555f4e6d7564 in main /home/jkt/work/prog/_build/czechlight-clang16-asan-ubsan/target/include/doctest/doctest.h:6805:71
    #13 0x7f0d10c3dacd in __libc_start_call_main (/nix/store/1x4ijm9r1a88qk7zcmbbfza324gx1aac-glibc-2.37-8/lib/libc.so.6+0x23acd) (BuildId: 344aaad51978b8c259311fba5dc7581f830bad5a)

SUMMARY: AddressSanitizer: 159 byte(s) leaked in 3 allocation(s).
```
The C++ wrapper is careful to call the respective `free` on both of the returned nodes (as long as they are not `NULL`), which means that the leak is in libyang itself (and there has been no change in `libyang-cpp` and this used to pass the tests, correctly throwing an exception).

**Comment by michalvasko** [comment]
My bad, a test has been added. Fixed but it seems an old bug has just manifested, no new ones were added.
