### ISSUE TITLE
libyang will coredump in this strcmp because ns is null

### ISSUE THREAD

**Issue by lyzliyuzhi91** [CESNET/libyang#2097]
https://github.com/CESNET/libyang/blob/8b0b910a2dcb7360cb5b0aaefbd1338271d50946/src/printer_xml.c#L71C52-L71C52

stack:
```
#0  0x00007fa1560f52be in __strcmp_sse2_unaligned () from /lib64/libc.so.6
#1  0x00007fa15687758f in xml_print_ns (pctx=0x7fff2f752d70, ns=0x0, new_prefix=0x0, prefix_opts=2)
    at /data/lcx/opensource/ly/libyang/src/printer_xml.c:71
#2  0x00007fa1568777bf in xml_print_ns_opaq (pctx=0x7fff2f752d70, format=LY_VALUE_XML, name=0x5560f9605b50, prefix_opts=2)
    at /data/lcx/opensource/ly/libyang/src/printer_xml.c:113
#3  0x00007fa156877fcf in xml_print_opaq_open (pctx=0x7fff2f752d70, node=0x5560f9605b10)
    at /data/lcx/opensource/ly/libyang/src/printer_xml.c:301
#4  0x00007fa15687887b in xml_print_opaq (pctx=0x7fff2f752d70, node=0x5560f9605b10)
    at /data/lcx/opensource/ly/libyang/src/printer_xml.c:499
#5  0x00007fa156878b47 in xml_print_node (pctx=0x7fff2f752d70, node=0x5560f9605b10)
    at /data/lcx/opensource/ly/libyang/src/printer_xml.c:557
#6  0x00007fa156878992 in xml_print_opaq (pctx=0x7fff2f752d70, node=0x5560f9605c80)
    at /data/lcx/opensource/ly/libyang/src/printer_xml.c:519
#7  0x00007fa156878b47 in xml_print_node (pctx=0x7fff2f752d70, node=0x5560f9605c80)
    at /data/lcx/opensource/ly/libyang/src/printer_xml.c:557
#8  0x00007fa156878372 in xml_print_inner (pctx=0x7fff2f752d70, node=0x5560f95fddf0)
    at /data/lcx/opensource/ly/libyang/src/printer_xml.c:396
#9  0x00007fa156878bba in xml_print_node (pctx=0x7fff2f752d70, node=0x5560f95fddf0)
    at /data/lcx/opensource/ly/libyang/src/printer_xml.c:565
#10 0x00007fa156878677 in xml_print_anydata (pctx=0x7fff2f752d70, node=0x5560f95fe410)
    at /data/lcx/opensource/ly/libyang/src/printer_xml.c:452
#11 0x00007fa156878bea in xml_print_node (pctx=0x7fff2f752d70, node=0x5560f95fe410)
    at /data/lcx/opensource/ly/libyang/src/printer_xml.c:573
#12 0x00007fa156878372 in xml_print_inner (pctx=0x7fff2f752d70, node=0x5560f95fe090)
    at /data/lcx/opensource/ly/libyang/src/printer_xml.c:396
#13 0x00007fa156878bba in xml_print_node (pctx=0x7fff2f752d70, node=0x5560f95fe090)
    at /data/lcx/opensource/ly/libyang/src/printer_xml.c:565
#14 0x00007fa156878d94 in xml_print_data (out=0x5560f9605bc0, root=0x5560f95fe090, options=39)
    at /data/lcx/opensource/ly/libyang/src/printer_xml.c:612
#15 0x00007fa156876f35 in lyd_print_ (out=0x5560f9605bc0, root=0x5560f95fe090, format=LYD_XML, options=39)
    at /data/lcx/opensource/ly/libyang/src/printer_data.c:33
#16 0x00007fa156877255 in lyd_print_mem (strp=0x7fff2f752e88, root=0x5560f95fe090, format=LYD_XML, options=39)
    at /data/lcx/opensource/ly/libyang/src/printer_data.c:100
```

module:
```
module bla-st-config {
    namespace "urn:test:bla:bla-st-config";
    prefix bla-st-config;

    container c1 {
        list l1 {
            key k1;
            leaf k1 { type string; }
            leaf v1 { type string; }
        }
    }
}
```

message:
```
"<edit-config xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\"><target><running/></target><config><c1 xmlns=\"urn:test:bla:bla-st-config\" xmlns:xxx=\"urn:test:bla:bla-st-config\"><l1><bla-st-config:kn>abc</bla-st-config:kn></l1></c1></config></edit-config>"
```
where `kn` is not defined in module.

code:
```
    struct ly_in *in = NULL;
    LY_ERR err = ly_in_new_memory(action_buf, &in);  // action_buf is the message above
    if (err != LY_SUCCESS) {
        return NULL;
    }

    lyd_node_t *tree, *action;
    err = lyd_parse_op(ly_ctx, NULL, in, LYD_XML, LYD_TYPE_RPC_YANG, &tree, &action);
    if (err != LY_SUCCESS) {
        ly_in_free(in, 0);
        return NULL;
    }

   // .... codes not concerned
 
    char *new_buf = NULL;
    uint32_t print_opts = LYD_PRINT_KEEPEMPTYCONT | LYD_PRINT_WITHSIBLINGS | LYD_PRINT_SHRINK | LYD_PRINT_WD_ALL;
    err = lyd_print_mem(&new_buf, tree, LYD_XML, print_opts);  // coredump here
```

of course, the `message` is invalid because prefix `bla-st-config` has no namespace defined, but it should not coredump anyway for an invalid message I think.
Thanks.

**Comment by michalvasko** [comment]
Alright, fixed.

**Comment by lyzliyuzhi91** [comment]
ok
