### ISSUE TITLE
validation doesn't discover inavlid leafref

### ISSUE THREAD

**Issue by lukasmacko** [CESNET/libyang#218]
```C
#include <stdio.h>
#include <stdlib.h>
#include <libyang/libyang.h>

int main(int argc, char **argv) {
   struct ly_ctx *ctx = ly_ctx_new(".");
   ly_ctx_load_module(ctx, "test-module", NULL);
   struct lyd_node *root = lyd_parse_path(ctx, "in.xml", LYD_XML, LYD_OPT_CONFIG);

   /* set invalid leafref */
   lyd_new_path(root, ctx, "/test-module:university/classes/class[title='CCNA']/student[name='nameB']/age", "18", 0, LYD_PATH_OPT_UPDATE);


   char *out = NULL;
   lyd_print_mem(&out, root, LYD_XML, LYP_FORMAT| LYP_WITHSIBLINGS);
   puts(out);
   free(out);

   if (0 == lyd_validate(&root, LYD_OPT_CONFIG, NULL)) {
      puts("validation passed");
   } else {
      puts("validation failed");
   }
   lyd_free_withsiblings(root);
   ly_ctx_destroy(ctx, NULL);
   return 0;
}
```
Input data `ìn.xml`
```XML
<university xmlns="urn:ietf:params:xml:ns:yang:test-module">
  <students>
    <student>
      <name>nameA</name>
      <age>19</age>
    </student>
    <student>
      <name>nameB</name>
      <age>17</age>
    </student>
    <student>
      <name>nameC</name>
      <age>18</age>
    </student>
  </students>
  <classes>
    <class>
      <title>CCNA</title>
      <student>
        <name>nameB</name>
        <age>17</age>
      </student>
      <student>
        <name>nameC</name>
      </student>
    </class>
  </classes>
</university>
```

test-module.yang
```YANG
module test-module {
  yang-version 1.1;
  namespace "urn:ietf:params:xml:ns:yang:test-module";

  prefix tm;

  import ietf-inet-types {
    prefix inet;
  }

  organization "organization";
  description
    "example yang module";
  contact
    "example@example.org";


  container university {
    container students {
        list student {
            ordered-by user;
            config true;

            key "name";

            leaf name {
                type string;
            }

            leaf age {
                type uint8;
            }
        }
    }

    container classes {
        list class {
            config true;

            key "title";

            leaf title {
                type string;
            }

            list student {
                key "name";

                leaf name {
                    type leafref {
                        path "../../../../students/student/name";
                    }
                }
                leaf age {
                    type leafref {
                        path "../../../../students/student[name = current()/../name]/age";
                    }
                }
            }
        }
    }
  }


```

**Comment by michalvasko** [comment]
Hi,
thanks, should be fixed.

Regards,
Michal

**Comment by lukasmacko** [comment]
The error is detected however `lyd_validation` still returns 0.

**Comment by michalvasko** [comment]
Yes, because `lyd_new_path` fails and does not do any change, so the tree stays valid.

**Comment by lukasmacko** [comment]
hmm, I wondering if this is correct approach. Let's assume I want to create leafref first and the referenced node in the next step and validate all, in the end. I think this is valid scenario.

With this modification I got SIGSEGV
```C
#include <stdio.h>
#include <stdlib.h>
#include <libyang/libyang.h>

int main(int argc, char **argv) {
   struct ly_ctx *ctx = ly_ctx_new(".");
   ly_ctx_load_module(ctx, "test-module", NULL);
   struct lyd_node *root = lyd_parse_path(ctx, "in.xml", LYD_XML, LYD_OPT_CONFIG);

   /* set invalid leafref */
   lyd_new_path(root, ctx, "/test-module:university/classes/class[title='CCNA']/student[name='nameXY']/age", "18", 0, LYD_PATH_OPT_UPDATE);

   char *out = NULL;
   lyd_print_mem(&out, root, LYD_XML, LYP_FORMAT| LYP_WITHSIBLINGS);
   puts(out);
   free(out);

   if (0 == lyd_validate(&root, LYD_OPT_CONFIG, ctx)) {
      puts("validation passed");
   } else {
      puts("validation failed");
   }
   lyd_free_withsiblings(root);
   ly_ctx_destroy(ctx, NULL);
   return 0;
}
```
```
(gdb) bt
#0  0x00007ffff7b12220 in resolve_path_predicate_data (pred=0x608896 "/age", node=0x612740, node_match=0x7fffffffd700, parsed=0x7fffffffd6a0) at /home/lukas/playground/libyang/src/resolve.c:3532
#1  0x00007ffff7b125f8 in resolve_path_arg_data (node=0x612740, path=0x60887c "[name = current()/../name]/age", ret=0x7fffffffd700) at /home/lukas/playground/libyang/src/resolve.c:3652
#2  0x00007ffff7b1acb0 in resolve_leafref (leaf=0x612740, type=0x613940) at /home/lukas/playground/libyang/src/resolve.c:6790
#3  0x00007ffff7b1afe1 in resolve_unres_data_item (node=0x612740, type=UNRES_LEAFREF) at /home/lukas/playground/libyang/src/resolve.c:6875
#4  0x00007ffff7b1baa6 in resolve_unres_data (unres=0x60c6b0, root=0x7fffffffd8f0, options=1) at /home/lukas/playground/libyang/src/resolve.c:7126
#5  0x00007ffff7b7ccb8 in lyd_defaults_add_unres (root=0x7fffffffd8f0, options=1, ctx=0x602010, data_tree=0x609600, act_notif=0x0, unres=0x60c6b0) at /home/lukas/playground/libyang/src/tree_data.c:5749
#6  0x00007ffff7b783b8 in lyd_validate (node=0x7fffffffd8f0, options=1, var_arg=0x602010) at /home/lukas/playground/libyang/src/tree_data.c:3778
#7  0x0000000000400aa1 in main (argc=1, argv=0x7fffffffd9f8) at main.c:18
```
