### ISSUE TITLE
How does libyang do cross-datastore validation?

### ISSUE THREAD

**Issue by classcwnd** [CESNET/libyang#26]
I added following models, and do validation for datastore.xml, but got below errors, is this normal or a bug? From my point, it is a right datastore and shall not report error.
Attached [datastore.xml](https://github.com/CESNET/libyang/files/126532/datastore.zip) 
[models.tar](https://github.com/CESNET/libyang/files/123549/models.zip)

```
> clear
> add ietf-interfaces@2014-05-08.yin
> add iana-if-type.yin
> add ericsson-context-ipos@2015-12-07.yin
> add ericsson-interfaces-ext-ipos@2015-12-07.yin
> data datastore.xml
libyang[0]: Parser fails around the line 7.
libyang[0]: Unknown element "contexts".
libyang[0]: There are unresolved data items left.
Failed to parse data.
```

**Comment by rkrejci** [comment]
libyang expects that all content of the datastore is provided in the input data. So, just put all data, from all models, into the datastore.xml. With the command you used, yanglint will accept not a well-formed datastore.xml with multiple top-levele XML elements - see the updated yanglint examples README in the devel branch.

**Comment by classcwnd** [comment]
Thanks,
BTW, what is the difference between master and devel branch?
which branch shall we use for better?

**Comment by classcwnd** [comment]
Hi

I used level branch and read the *Multiple top-level elements in a single document* method.
I changed the original datastore.xml to [datastore_good.xml](https://github.com/CESNET/libyang/files/126986/datastore_good.zip) with the format of  "Multiple top-level elements in a single document". 
Unfortunately, I met segmentation fault after I use ```data -s datastore_good.xml```

```
> add ietf-interfaces@2014-05-08.yin
> add iana-if-type.yin
> add ericsson-contexts-ipos@2015-12-07.yin
> add ericsson-context-ipos@2015-12-07.yin
> add ericsson-interfaces-ext-ipos@2015-12-07.yin
> data -s datastore_good.xml 

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b94b3e in lys_getnext (last=0x0, parent=0x644750, module=0x0, options=1)
    at /project/swbuild82/eyyuppg/libnetconf/integration/new4/netopeer/libyang/src/tree_schema.c:253
253	        next = last->next;
(gdb) bt
#0  0x00007ffff7b94b3e in lys_getnext (last=0x0, parent=0x644750, module=0x0, options=1)
    at /project/swbuild82/eyyuppg/libnetconf/integration/new4/netopeer/libyang/src/tree_schema.c:253
#1  0x00007ffff7b94c83 in check_mand_getnext (last=0x0, parent=0x644750, module=0x0)
    at /project/swbuild82/eyyuppg/libnetconf/integration/new4/netopeer/libyang/src/tree_schema.c:314
#2  0x00007ffff7b951f8 in ly_check_mandatory (data=0x63ffd0, schema=0x6170a0)
    at /project/swbuild82/eyyuppg/libnetconf/integration/new4/netopeer/libyang/src/tree_schema.c:497
#3  0x00007ffff7b74532 in lyv_data_content (node=0x63ffd0, options=1280, line=15, unres=0x60f2f0)
    at /project/swbuild82/eyyuppg/libnetconf/integration/new4/netopeer/libyang/src/validation.c:436
#4  0x00007ffff7b9155f in xml_parse_data (ctx=0x62b240, xml=0x615560, schema_parent=0x0, parent=0x643a40, prev=0x642f90, options=1280, 
    unres=0x60f2f0, result=0x7fffffffcc88) at /project/swbuild82/eyyuppg/libnetconf/integration/new4/netopeer/libyang/src/parser_xml.c:396
#5  0x00007ffff7b914b4 in xml_parse_data (ctx=0x62b240, xml=0x642cd0, schema_parent=0x0, parent=0x0, prev=0x61c770, options=1280, 
    unres=0x60f2f0, result=0x7fffffffcd38) at /project/swbuild82/eyyuppg/libnetconf/integration/new4/netopeer/libyang/src/parser_xml.c:381
#6  0x00007ffff7b91951 in lyd_parse_xml (ctx=0x62b240, root=0x7fffffffce90, options=1280)
    at /project/swbuild82/eyyuppg/libnetconf/integration/new4/netopeer/libyang/src/parser_xml.c:479
#7  0x00007ffff7b9c153 in lyd_parse_ (ctx=0x62b240, parent=0x0, 
    data=0x7ffff7ff8000 "<if:interfaces xmlns:if=\"urn:ietf:params:xml:ns:yang:ietf-interfaces\" xmlns:ianaift=\"urn:ietf:params:xml:ns:yang:iana-if-type\" xmlns:ifxipos=\"urn:rdns:com:ericsson:oammodel:ericsson-interfaces-ext-ipo"..., format=LYD_XML, options=1280)
    at /project/swbuild82/eyyuppg/libnetconf/integration/new4/netopeer/libyang/src/tree_data.c:71
#8  0x00007ffff7b9c322 in lyd_parse_data_ (ctx=0x62b240, 
    data=0x7ffff7ff8000 "<if:interfaces xmlns:if=\"urn:ietf:params:xml:ns:yang:ietf-interfaces\" xmlns:ianaift=\"urn:ietf:params:xml:ns:yang:iana-if-type\" xmlns:ifxipos=\"urn:rdns:com:ericsson:oammodel:ericsson-interfaces-ext-ipo"..., format=LYD_XML, options=1280, 
    ap=0x7fffffffcf40) at /project/swbuild82/eyyuppg/libnetconf/integration/new4/netopeer/libyang/src/tree_data.c:109
#9  0x00007ffff7b9c5fe in lyd_parse_fd (ctx=0x62b240, fd=3, format=LYD_XML, options=1280)
    at /project/swbuild82/eyyuppg/libnetconf/integration/new4/netopeer/libyang/src/tree_data.c:150
#10 0x00007ffff7b9c7b9 in lyd_parse_path (ctx=0x62b240, path=0x60e758 "datastore_good.xml", format=LYD_XML, options=1280)
---Type <return> to continue, or q <return> to quit---
 
```

**Comment by rkrejci** [comment]
ad to master vs. devel branch question - devel changes more frequently and all bugfixes are applied to devel (some of them are applied also to master, but not all of them). From our perspective, it is better if users use the devel branch, because we can get feedback and bug reports earlier, but from users perspective, devel is more unstable. So, it is up to you which branch you will pick up :)
