### ISSUE TITLE
Issue with lys_set_disabled() + lys_set_enabled()

### ISSUE THREAD

**Issue by rwestphal** [CESNET/libyang#559]
Hi,

I want to load a module with several YANG deviations but disable it temporarily to calculate a few things based on the original module (I want to calculate the coverage provided by my module translator). I'm using `lys_set_disabled()` and it's working flawlessly, but when I reactive the deviations using `lys_set_enabled()` I get the following backtrace:
```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".deviations2: /mnt/renato/git/northbound/lang-c/libyang/src/tree_schema.c:4277: lys_switch_deviation: Assertion `parent->child && !parent->child->next && (parent->ch
ild->nodetype == (inout->nodetype == LYS_INPUT ? LYS_OUTPUT : LYS_INPUT))' failed.


Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff773f3fa in __GI_abort () at abort.c:89
#2  0x00007ffff7736e37 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x7ffff7bb5588 "parent->child && !parent->child->next && (parent->child->nodetype == (inout->nodetype == LYS_INPUT ? LYS_OUTPUT : LYS_INPUT))", f
ile=file@entry=0x7ffff7bb4e20 "/mnt/renato/git/northbound/lang-c/libyang/src/tree_schema.c", line=line@entry=4277, function=function@entry=0x7ffff7bb5bc0 <__PRETTY_FUNCTION__.10040> "lys_switch_deviation") at assert.c:92
#3  0x00007ffff7736ee2 in __GI___assert_fail (assertion=0x7ffff7bb5588 "parent->child && !parent->child->next && (parent->child->nodetype == (inout->nodetype == LYS_INPUT ? LYS_OUTPUT : LYS_INPUT))", file=0x7ffff7bb4e20 "/mnt/renato/git/n
orthbound/lang-c/libyang/src/tree_schema.c", line=4277, function=0x7ffff7bb5bc0 <__PRETTY_FUNCTION__.10040> "lys_switch_deviation") at assert.c:101
#4  0x00007ffff7b4ce5a in lys_switch_deviation (dev=0x5555559234b0, module=0x55555591a950, unres=0x55555575fb60) at /mnt/renato/git/northbound/lang-c/libyang/src/tree_schema.c:4276
#5  0x00007ffff7b4d44f in apply_dev (dev=0x5555559234b0, module=0x55555591a950, unres=0x55555575fb60) at /mnt/renato/git/northbound/lang-c/libyang/src/tree_schema.c:4391
#6  0x00007ffff7b4d70f in lys_sub_module_apply_devs_augs (module=0x55555591a950) at /mnt/renato/git/northbound/lang-c/libyang/src/tree_schema.c:4453
#7  0x00007ffff7abfe45 in lys_set_enabled (module=0x55555591a950) at /mnt/renato/git/northbound/lang-c/libyang/src/context.c:1279
#8  0x0000555555554a26 in main (argc=1, argv=0x7fffffffe9a8) at deviations2.c:29
```

This only happen when reactivating the _frr-deviations-ietf-rip.yang_ module, all my other deviation modules are reactivated just fine.

Code to reproduce the problem:
```c
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <stdint.h>
#include <string.h>
#include <err.h>

#include <libyang/libyang.h>

int main(int argc, char *argv[])
{
        struct ly_ctx *ly_ctx;
        const struct lys_module *module;
        
        /* Initialization. */
        ly_ctx = ly_ctx_new(NULL, 0);
        if (!ly_ctx)
                errx(1, "ly_ctx_new()");
        
        ly_ctx_set_searchdir(ly_ctx, "/usr/local/share/yang/");
        
        /* Load YANG modules. */
        ly_ctx_load_module(ly_ctx, "ietf-interfaces", NULL);
        ly_ctx_load_module(ly_ctx, "ietf-rip", NULL);

        /* Load deviations. */
        module = ly_ctx_load_module(ly_ctx, "frr-deviations-ietf-rip", NULL);
        lys_set_disabled(module);
        lys_set_enabled(module);

        /* Cleanup. */
        ly_ctx_destroy(ly_ctx, NULL);
        
        return 0;
}
```

YANG models:
* ietf-interfaces.yang: https://raw.githubusercontent.com/YangModels/yang/master/standard/ietf/RFC/ietf-interfaces%402018-02-20.yang
* ietf-rip.yang: https://raw.githubusercontent.com/YangModels/yang/master/experimental/ietf-extracted-YANG-modules/ietf-rip%402018-02-03.yang
* frr-deviations-ietf-rip.yang: https://gist.githubusercontent.com/rwestphal/0a8caa319c570b712842ee8aa9a635df/raw/a45afa6b8b538595e3603aac5187aad0939bf92a/frr-deviations-ietf-rip.yang

Thanks in advance!

**Comment by michalvasko** [comment]
Hi,
should work now.

Regards,
Michal
