### ISSUE TITLE
src/validation.c:370:60: runtime error: member access within null pointer of type 'struct lyd_node_leaf_list'

### ISSUE THREAD

**Issue by jktjkt** [CESNET/libyang#613]
I'm getting the following segfault when importing data:
```
libyang/src/validation.c:370:60: runtime error: member access within null pointer of type 'struct lyd_node_leaf_list'
AddressSanitizer:DEADLYSIGNAL
=================================================================
ERROR: AddressSanitizer: SEGV on unknown address 0x000000000038 (pc 0x7f0598fdd726 bp 0x7ffd93947e60 sp 0x7ffd93947d50 T0)
The signal is caused by a READ memory access.
Hint: address points to the zero page.
    #0 0x7f0598fdd725 in lyv_data_unique libyang/src/validation.c:370
    #1 0x7f05990e489a in lyd_parse_json libyang/src/parser_json.c:1488
    #2 0x7f0599239edf in lyd_parse_ libyang/src/tree_data.c:927
    #3 0x7f059923a7f7 in lyd_parse_data_ libyang/src/tree_data.c:993
    #4 0x7f059923ab71 in lyd_parse_fd_ libyang/src/tree_data.c:1028
    #5 0x7f059923ad63 in lyd_parse_fd libyang/src/tree_data.c:1042
    #6 0x5589e61ebea9 in srcfg_import_datastore sysrepo/src/executables/sysrepocfg.c:801
    #7 0x5589e61f2061 in srcfg_import_operation sysrepo/src/executables/sysrepocfg.c:1191
    #8 0x5589e61f9948 in main sysrepo/src/executables/sysrepocfg.c:2034
    #9 0x7f0596d35c4d in __libc_start_main ../csu/libc-start.c:295
    #10 0x5589e61de3c9 in _start (/opt/nc/bin/sysrepocfg+0x1d3c9)
```
I'll provide the required models and data via a private mail. This is on CESNET/libyang@b9c346bb1d5eb3b400398a862eed251138222a43 and sysrepo/sysrepo@5e7652c20ed2c02bfac53ad3355fa825bc92ab90.

**Comment by jktjkt** [comment]
It seems that this happens when the JSON input for a list element does not contain all nodes specified in the list's `key` statement.

**Comment by michalvasko** [comment]
Hi,
I think I have accidentally fixed this problem in commit 185b527a2b4b9f69b8c0bdc072f8bb307ce0f55a. I cannot reproduce it, anyway. Can you please try again with most recent libyang?

Regards,
Michal
