### ISSUE TITLE
Confusing "Assertion `leaf->validity & LYD_VAL_LEAFREF' failed." error

### ISSUE THREAD

**Issue by rjarry** [CESNET/libyang#614]
Hello,

Here is how to reproduce the problem:

Test program:

```c
/* example.c */
#include <libyang/libyang.h>

void main(void) {
        struct ly_ctx *ctx = ly_ctx_new(NULL, 0);
        lys_parse_path(ctx, "example.yang", LYS_IN_YANG);
        lyd_parse_path(ctx, "example.json", LYD_JSON,
                       LYD_OPT_TRUSTED | LYD_OPT_CONFIG | LYD_OPT_STRICT);
}
```

YANG module:

```yang
// example.yang
module example {
  yang-version 1.1;
  namespace "urn:example";
  prefix "ex";

  typedef oid {
    type string;
  }

  typedef auth-level {
    type enumeration {
      enum read-only;
      enum read-write;
    }
  }

  typedef frequency {
    type string {
      pattern "[0-9]+[smhdw]";
    }
  }

  container x {
    list view {
      key "name";

      leaf name {
        type string;
      }
      list subtree {
        min-elements 1;
        key "oid";
        leaf oid {
          type oid;
        }
        leaf included {
          type boolean;
          default true;
        }
      }
    } // list view

    list community {
      key "name";

      leaf name {
        type string;
      }
      leaf authorization {
        type auth-level;
        mandatory true;
      }
      leaf source {
        type string;
      }
      leaf view {
        type leafref {
          path "../../view/name";
        }
      }
    } // list community

    container access-control {

      list user {
        key "name";

        leaf name {
          type string {
            pattern "[a-zA-Z0-9][-_.a-zA-Z0-9]*";
          }
        }
        leaf auth-password {
          mandatory true;
          type string {
            length "8..max";
          }
        }
        leaf auth-method {
          type enumeration {
            enum md5;
            enum sha;
          }
          default sha;
        }
        leaf priv-password {
          type string {
            length "8..max";
          }
        }
        leaf priv-protocol {
          type enumeration {
            enum aes;
            enum des;
          }
          default aes;
        }
      } // list user

      list group {
        key "name";

        leaf name {
          type string;
        }
        leaf-list user {
          min-elements 1;
          type leafref {
            path "../../user/name";
          }
        }
        leaf security-level {
          mandatory true;
          type enumeration {
            enum auth;
            enum priv;
          }
        }
        leaf view {
          type leafref {
            path "../../../view/name";
          }
        }
        leaf authorization {
          type auth-level;
          default read-only;
        }
      } // list group
    } // container access-control

    container traps {
      list destination {
        key "host";

        leaf host {
          type string;
        }
        leaf port {
          type uint16;
          default 162;
        }
        leaf protocol {
          type enumeration {
            enum udp;
            enum tcp;
            enum udp6;
            enum tcp6;
          }
          default udp;
        }
        leaf notification-type {
          type enumeration {
            enum TRAP;
            enum TRAP2;
            enum INFORM;
          }
          mandatory true;
        }
        leaf community {
          type leafref {
            path "../../../community/name";
          }
          mandatory true;
        }
      } // list sink
    } // container traps
  } // grouping x
}
```

JSON data:

```json
{
  "example:x": {
    "view": [
      {
        "name": "restricted",
        "subtree": [
          {
            "oid": ".1.2.3",
            "included": true
          },
          {
            "oid": ".1.2.3.4.5",
            "included": false
          }
        ]
      }
    ],
    "community": [
      {
        "view": "restricted",
        "name": "public",
        "authorization": "read-only"
      },
      {
        "name": "private",
        "authorization": "read-only",
        "source": "10.0.0.0/24"
      }
    ],
    "traps": {
      "destination": [
        {
          "community": "public",
          "notification-type": "INFORM",
          "host": "3ffe::3ad5:47ff:fe15:e694"
        },
        {
          "community": "public",
          "notification-type": "TRAP",
          "host": "10.0.0.200"
        },
        {
          "community": "private",
          "notification-type": "TRAP2",
          "host": "localhost",
          "port": 4000
        }
      ]
    },
    "access-control": {
      "group": [
        {
          "name": "admins",
          "security-level": "priv",
          "authorization": "read-write",
          "user": [
            "jean-jacques"
          ]
        },
        {
          "view": "restricted",
          "name": "janitors",
          "security-level": "auth",
          "authorization": "read-only",
          "user": [
            "lionel"
          ]
        }
      ],
      "user": [
        {
          "name": "lionel",
          "auth-password": "very secret 1"
        },
        {
          "priv-password": "very secret 3",
          "name": "jean-jacques",
          "auth-password": "very secret 2"
        }
      ]
    }
  }
}
```

```
$ gcc example.c -o example -l yang
$ ulimit -S -c unlimited example
$ ./example
example: src/resolve.c:8028: resolve_unres_data_item: Assertion `leaf->validity & LYD_VAL_LEAFREF' failed.
Aborted (core dumped)
$ gdb -c /tmp/core.example.13298 example 
(gdb) bt
#0  0x00007fccddc69428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007fccddc6b02a in __GI_abort () at abort.c:89
#2  0x00007fccddc61bd7 in __assert_fail_base (fmt=<optimized out>, 
    assertion=assertion@entry=0x7fccde106908 "leaf->validity & LYD_VAL_LEAFREF", 
    file=file@entry=0x7fccde105120 "src/resolve.c", line=line@entry=8028, 
    function=function@entry=0x7fccde1072f0 <__PRETTY_FUNCTION__.9851> "resolve_unres_data_item") at assert.c:92
#3  0x00007fccddc61c82 in __GI___assert_fail (assertion=0x7fccde106908 "leaf->validity & LYD_VAL_LEAFREF", 
    file=0x7fccde105120 "src/resolve.c", line=8028, 
    function=0x7fccde1072f0 <__PRETTY_FUNCTION__.9851> "resolve_unres_data_item") at assert.c:101
#4  0x00007fccde02f90e in resolve_unres_data_item (node=0xfbec70, type=UNRES_LEAFREF, ignore_fail=1, failed_when=0x0)
    at src/resolve.c:8028
#5  0x00007fccde0305c7 in resolve_unres_data (ctx=0xfa5010, unres=0xfbb680, root=0x7ffc177f2b40, options=8705)
    at src/resolve.c:8354
#6  0x00007fccde0bd4b1 in lyd_defaults_add_unres (root=0x7ffc177f2b40, options=8705, ctx=0xfa5010, data_tree=0x0, 
    act_notif=0x0, unres=0xfbb680, wd=1) at src/tree_data.c:7248
#7  0x00007fccde06fb80 in lyd_parse_json (ctx=0xfa5010, 
    data=0x7fccde566000 <error: Cannot access memory at address 0x7fccde566000>, options=8705, rpc_act=0x0, 
    data_tree=0x0, yang_data_name=0x0) at src/parser_json.c:1489
#8  0x00007fccde0ad8d3 in lyd_parse_ (ctx=0xfa5010, rpc_act=0x0, 
    data=0x7fccde566000 <error: Cannot access memory at address 0x7fccde566000>, format=LYD_JSON, options=8705, 
    data_tree=0x0, yang_data_name=0x0) at src/tree_data.c:927
#9  0x00007fccde0adc24 in lyd_parse_data_ (ctx=0xfa5010, 
    data=0x7fccde566000 <error: Cannot access memory at address 0x7fccde566000>, format=LYD_JSON, options=8705, 
    ap=0x7ffc177f2ce0) at src/tree_data.c:993
#10 0x00007fccde0addfc in lyd_parse_fd_ (ctx=0xfa5010, fd=3, format=LYD_JSON, options=8705, ap=0x7ffc177f2ce0)
    at src/tree_data.c:1028
#11 0x00007fccde0ae08c in lyd_parse_path (ctx=0xfa5010, path=0x400821 "example.json", format=LYD_JSON, options=8705)
    at src/tree_data.c:1067
#12 0x0000000000400787 in main ()
```

If I remove the `assert()` statement that fails, it seems to work fine. However, I'm not sure if that is the correct fix.

I added some debugging:

```diff
diff --git a/src/resolve.c b/src/resolve.c
index 4334c199f1a2..679b0bd9db03 100644
--- a/src/resolve.c
+++ b/src/resolve.c
@@ -8025,6 +8025,8 @@ resolve_unres_data_item(struct lyd_node *node, enum UNRES_ITEM type, int ignore_
     switch (type) {
     case UNRES_LEAFREF:
         assert(sleaf->type.base == LY_TYPE_LEAFREF);
+        printf("resolve_unres_data_item: ");
+        lyd_print_file(stdout, leaf, LYD_JSON, LYP_FORMAT | LYP_WD_ALL);
         assert(leaf->validity & LYD_VAL_LEAFREF);
         if ((ignore_fail == 1) || ((leaf->schema->flags & LYS_LEAFREF_DEP) && (ignore_fail == 2))) {
             req_inst = -1;
```

And here is the output:

```
$ ./example
resolve_unres_data_item: {
  "example:view": "restricted"
}
resolve_unres_data_item: {
  "example:view": "restricted"
}
example: src/resolve.c:8030: resolve_unres_data_item: Assertion `leaf->validity & LYD_VAL_LEAFREF' failed.
Aborted (core dumped)
```

**Comment by rjarry** [comment]
Oh sorry @michalvasco, I forgot to confirm that it fixed the problem.

Thanks again for your quick reaction :)
