### ISSUE TITLE
sysrepo test dm_test triggers an infinite loop

### ISSUE THREAD

**Issue by jktjkt** [CESNET/libyang#730]
After updating libyang from 9eeea666a71e88b73a493b881421cd9c7f364f04 to aec6d40e244da29aba0e9f43ed39ea8ff462a953, sysrepo's test `dm_test` gets stuck in something that looks like an infinite loop:
```
[ RUN      ] dm_event_notif_parse_test
[DBG] (np_init:809) Notification Processor initialized successfully.
[INF] (dm_init:2270) Initializing Data Manager, schema_search_dir=/home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/yang/, data_search_dir=/home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/
[DBG] (rp_session_start:4086) RP session start, session id=123456.
[DBG] (sr_locking_set_lock_fd:806) File /home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/referenced-data.persist has been locked
[DBG] (pm_load_data_tree:267) Persist data successfully loaded from file '/home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/referenced-data.persist'.
[DBG] (sr_locking_set_unlock_close_fd:875) File /home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/referenced-data.persist (fd = 3) has been unlocked
[DBG] (pm_get_module_info:1061) Returning info from 'referenced-data' persist file: module disabled, 0 subtrees enabled in running, 0 features enabled.
[DBG] (sr_locking_set_lock_fd:806) File /home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/test-module.persist has been locked
[DBG] (pm_load_data_tree:267) Persist data successfully loaded from file '/home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/test-module.persist'.
[DBG] (sr_locking_set_unlock_close_fd:875) File /home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/test-module.persist (fd = 3) has been unlocked
[DBG] (pm_get_module_info:1061) Returning info from 'test-module' persist file: module disabled, 0 subtrees enabled in running, 0 features enabled.
[DBG] (sr_locking_set_lock_fd:806) File /home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/test-module.persist has been locked
[DBG] (pm_load_data_tree:267) Persist data successfully loaded from file '/home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/test-module.persist'.
[DBG] (sr_locking_set_unlock_close_fd:875) File /home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/test-module.persist (fd = 3) has been unlocked
[DBG] (pm_get_module_info:1061) Returning info from 'test-module' persist file: module disabled, 0 subtrees enabled in running, 0 features enabled.
[DBG] (sr_locking_set_lock_fd:806) File /home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/referenced-data.persist has been locked
[DBG] (pm_load_data_tree:267) Persist data successfully loaded from file '/home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/referenced-data.persist'.
[DBG] (sr_locking_set_unlock_close_fd:875) File /home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/referenced-data.persist (fd = 3) has been unlocked
[DBG] (pm_get_module_info:1061) Returning info from 'referenced-data' persist file: module disabled, 0 subtrees enabled in running, 0 features enabled.
[DBG] (dm_load_data_tree_file:1403) Loaded module test-module: mtime sec=1552419477 nsec=709661474
[DBG] (dm_module_clb:507) CALLBACK FOR MODULE test-module (null)
[DBG] (sr_locking_set_lock_fd:806) File /home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/referenced-data.persist has been locked
[DBG] (pm_load_data_tree:267) Persist data successfully loaded from file '/home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/referenced-data.persist'.
[DBG] (sr_locking_set_unlock_close_fd:875) File /home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/referenced-data.persist (fd = 4) has been unlocked
[DBG] (pm_get_module_info:1061) Returning info from 'referenced-data' persist file: module disabled, 0 subtrees enabled in running, 0 features enabled.
[DBG] (sr_locking_set_lock_fd:806) File /home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/referenced-data.persist has been locked
[DBG] (pm_load_data_tree:267) Persist data successfully loaded from file '/home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/referenced-data.persist'.
[DBG] (sr_locking_set_unlock_close_fd:875) File /home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/referenced-data.persist (fd = 4) has been unlocked
[DBG] (pm_get_module_info:1061) Returning info from 'referenced-data' persist file: module disabled, 0 subtrees enabled in running, 0 features enabled.
[DBG] (dm_load_data_tree_file:1487) Usage count test-module incremented (value=1)
[INF] (dm_load_data_tree_file:1493) Data file /home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/test-module.startup loaded successfully
[DBG] (dm_load_data_tree_file:1403) Loaded module referenced-data: mtime sec=1552419477 nsec=754660637
[DBG] (dm_load_data_tree_file:1487) Usage count referenced-data incremented (value=1)
[INF] (dm_load_data_tree_file:1493) Data file /home/jkt/work/prog/_build/sysrepo/GCC_8_1_NETCONF-Debug/repository/data/referenced-data.startup loaded successfully
[DBG] (dm_get_data_info_internal:3034) Module referenced-data has been loaded
[DBG] (dm_data_info_free:300) Usage count referenced-data decremented (value=0)
[DBG] (dm_load_dependant_data:2254) Data tree referenced-data appended because of validation
[DBG] (dm_validate_data_info:2876) Validation succeeded for 'test-module' module
[DBG] (dm_get_data_info_internal:3034) Module test-module has been loaded
^C
Program received signal SIGINT, Interrupt.
0x00007ffff5184608 in lyht_find_collision (ht=0x6040002d3390, last=0x7fffffffc1f0, first=0x7fffef702780)
    at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/hash_table.c:457
457         i = (((unsigned char *)*last) - ht->recs) / ht->rec_size;
(gdb) bt
#0  0x00007ffff5184608 in lyht_find_collision (ht=0x6040002d3390, last=0x7fffffffc1f0, first=0x7fffef702780)
    at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/hash_table.c:457
#1  0x00007ffff51865f1 in lyht_insert_with_resize_cb (ht=0x6040002d3390, val_p=0x7fffef735da8, hash=171039992, resize_val_equal=0x0, match_p=0x0)
    at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/hash_table.c:609
#2  0x00007ffff51875cb in lyht_insert (ht=0x6040002d3390, val_p=0x7fffef735da8, hash=171039992, match_p=0x0)
    at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/hash_table.c:675
#3  0x00007ffff51838c2 in lyht_resize (ht=0x6040002d3390, enlarge=1) at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/hash_table.c:383
#4  0x00007ffff51874db in lyht_insert_with_resize_cb (ht=0x6040002d3390, val_p=0x7fffffffc4b0, hash=171039992, resize_val_equal=0x0, match_p=0x0)
    at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/hash_table.c:658
#5  0x00007ffff51875cb in lyht_insert (ht=0x6040002d3390, val_p=0x7fffffffc4b0, hash=171039992, match_p=0x0)
    at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/hash_table.c:675
#6  0x00007ffff545e4c8 in _lyd_insert_hash (node=0x607000702ef0, keyless_list_check=1)
    at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/tree_data.c:449
#7  0x00007ffff545e5fa in lyd_insert_hash (node=0x607000702ef0) at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/tree_data.c:466
#8  0x00007ffff52f5f42 in xml_parse_data (ctx=0x60d00006cfe0, xml=0x60700065d490, parent=0x60700065d6c0, first_sibling=0x60700065d730, prev=0x607000702e80, options=8768, 
    unres=0x6040002d3350, result=0x7fffffffc990, act_notif=0x7fffffffce90, yang_data_name=0x0)
    at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/parser_xml.c:497
#9  0x00007ffff52f6236 in xml_parse_data (ctx=0x60d00006cfe0, xml=0x60700065d3b0, parent=0x60700065d650, first_sibling=0x60700065d6c0, prev=0x0, options=8768, unres=0x6040002d3350, 
    result=0x7fffffffcc40, act_notif=0x7fffffffce90, yang_data_name=0x0) at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/parser_xml.c:510
#10 0x00007ffff52f6236 in xml_parse_data (ctx=0x60d00006cfe0, xml=0x60700065d340, parent=0x0, first_sibling=0x60700065d650, prev=0x0, options=8768, unres=0x6040002d3350, 
    result=0x7fffffffce50, act_notif=0x7fffffffce90, yang_data_name=0x0) at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/parser_xml.c:510
#11 0x00007ffff52f8bc9 in lyd_parse_xml (ctx=0x60d00006cfe0, root=0x7fffffffd0f0, options=8768)
    at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/libyang/src/parser_xml.c:680
#12 0x0000555555bec4fa in dm_parse_event_notif (rp_ctx=0x613000073d80, session=0x613000078a80, sr_mem=0x0, notification=0x6040002c7810, api_variant=SR_API_VALUES)
    at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/sysrepo/src/data_manager.c:6935
#13 0x00005555559c5339 in dm_event_notif_parse_test (state=0x617000000300) at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/sysrepo/tests/dm_test.c:779
#14 0x00007ffff6c0a3e4 in cmocka_run_one_test_or_fixture (function_name=0x555555d704c0 "dm_event_notif_parse_test", test_func=0x5555559c4d5f <dm_event_notif_parse_test>, 
    setup_func=setup_func@entry=0x0, teardown_func=teardown_func@entry=0x0, state=<optimized out>, state@entry=0x617000000300, heap_check_point=heap_check_point@entry=0x0)
    at /var/tmp/portage/dev-util/cmocka-1.0.1/work/cmocka-1.0.1/src/cmocka.c:2305
#15 0x00007ffff6c0ac59 in cmocka_run_one_tests (test_state=0x6170000002f0) at /var/tmp/portage/dev-util/cmocka-1.0.1/work/cmocka-1.0.1/src/cmocka.c:2413
#16 _cmocka_run_group_tests (group_name=0x555555d70140 "tests", tests=<optimized out>, num_tests=16, group_setup=<optimized out>, group_teardown=0x0)
    at /var/tmp/portage/dev-util/cmocka-1.0.1/work/cmocka-1.0.1/src/cmocka.c:2518
#17 0x00005555559cb292 in main () at /home/jkt/work/cesnet/gerrit/CzechLight/cla-sysrepo/submodules/dependencies/sysrepo/tests/dm_test.c:1146
```

**Comment by jktjkt** [comment]
I just bisected that commit range. The first offending commit is dbc405839b418d380d223895bfcdadd1b02dfdca.

**Comment by michalvasko** [comment]
Hi,
sorry about that, it should work now.

Regards,
Michal
