### ISSUE TITLE
cmake -DJAVASCRIPT_BINDING=ON failing with missing header files

### ISSUE THREAD

**Issue by demonicblue** [CESNET/libyang#87]
When i try to execute 
`cmake -DJAVASCRIPT_BINDING=ON`
it fails wit the following output:

```
ERROR - node.h not found
ERROR - v8.h not found
ERROR - uv.h not found
CMake Error at /home/demonicblue/Software/cmake-3.5.2-Linux-x86_64/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Nodejs (missing: NODEJS_INCLUDE_DIRS)
Call Stack (most recent call first):
  /home/demonicblue/Software/cmake-3.5.2-Linux-x86_64/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/FindNodejs.cmake:52 (find_package_handle_standard_args)
  swig/javascript/CMakeLists.txt:3 (find_package)
  CMakeLists.txt:177 (include)


-- Configuring incomplete, errors occurred!
See also "/home/demonicblue/Code/libyang/build/CMakeFiles/CMakeOutput.log".
See also "/home/demonicblue/Code/libyang/build/CMakeFiles/CMakeError.log".

```

Do i have to configure NODEJS_INCLUDE_DIRS manually? There is no relevant information in the JavaScript binding readme.

**Comment by mislavn** [comment]
What nodejs version do you have installed?
Do you have installed the npm package node-gyp?
The bindings are tested on node v5.x, with node-gyp, cmake version 3.5 and swig version 3.0.8.

You can build the bindings in the docker container.

[](https://hub.docker.com/r/sysrepo/sysrepo-netopeer2/)

with the commands:

`docker run -i -t --name sysrepo --rm sysrepo/sysrepo-netopeer2:latest bash
cd /opt/dev/libyang
mkdir build_node
cd build_node
cmake -DCMAKE_BUILD_TYPE:String="Release" -DCMAKE_INSTALL_PREFIX:PATH=/usr -DENABLE_BUILD_TESTS=OFF -DJAVASCRIPT_BINDING=ON ..
make
cd javascript/
node-gyp rebuild
ls build/Release/yang.node
`
The docker container is build with the following dockerfile:

[](https://github.com/sysrepo/docker-sysrepo-netopeer2/blob/master/Dockerfile)

You can take a look at the cmake, swig and nodejs version in the docker container.
You also have a npm libyang package:

https://www.npmjs.com/package/libyang

**Comment by demonicblue** [comment]
Thank you for the tip

I'm using swig 3.0.10, cmake 3.5.2 but I'm using node 4.4.7.
Any reason why you didn't test it on node LTS?

I currently don't have the ability to use docker so building without it would be great.

**Comment by mislavn** [comment]
We had before some trouble with node versions < 5.x and cmake, but now it should compile with 4.x, 5x and 6.x.

I have updated the dockerfile and docker container so it uses node 4.x now and the bindings compile.

The problem is probably in the find_package command:

find_package(Nodejs REQUIRED)

Where are the headers in your local system, in the docker container they are at "/usr/include/node".

What is your node-gyp version, mine is 3.4.0.

**Comment by demonicblue** [comment]
I'm also using node-gyp 3.4.0 but my system version of node is 0.10.26. This may be the issue as I'm using nvm for multiple node versions.

**Comment by mislavn** [comment]
Yes that is the problem, swig does not work well with node 0.10 and 0.12 I think.
I tried to use the default node (version 0.10.25) in Ubuntu 14.04, but it did not compile so I switched to newer versions.

**Comment by demonicblue** [comment]
Tried with node 6.3.0 through nvm but still no luck.
Also tried `npm install libyang` but with still getting errors using node 6.3.0

Any tips on what could be wrong?
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/demonicblue/.nvm/versions/node/v6.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 2.6.32-504.30.3.el6.x86_64
gyp ERR! command "/home/demonicblue/.nvm/versions/node/v6.3.0/bin/node" "/home/demonicblue/.nvm/versions/node/v6.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/demonicblue/Code/cmguitest/node_modules/libyang
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/demonicblue/Code/cmguitest/package.json'
npm WARN cmguitest No description
npm WARN cmguitest No repository field.
npm WARN cmguitest No README data
npm WARN cmguitest No license field.
npm ERR! Linux 2.6.32-504.30.3.el6.x86_64
npm ERR! argv "/home/demonicblue/.nvm/versions/node/v6.3.0/bin/node" "/home/demonicblue/.nvm/versions/node/v6.3.0/bin/npm" "install" "libyang"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! libyang@1.0.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libyang@1.0.11 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libyang package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libyang
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libyang
npm ERR! There is likely additional logging output above.
```

**Comment by mislavn** [comment]
I have tested it with node 6.3.0 in docker and everything works.

Dockerfile builds and in docker I can install libyang npm package.

```
root@7b19c117dff9:/tmp# node-gyp --version
v3.4.0
root@7b19c117dff9:/tmp# npm install libyang

> libyang@1.0.11 install /tmp/node_modules/libyang
> node-gyp rebuild

make: Entering directory `/tmp/node_modules/libyang/build'
  CC(target) Release/obj.target/libyang/src/yang_types.o
  CC(target) Release/obj.target/libyang/src/printer_json.o
  CC(target) Release/obj.target/libyang/src/printer_info.o
  CC(target) Release/obj.target/libyang/src/printer_tree.o
  CC(target) Release/obj.target/libyang/src/printer_xml.o
  CC(target) Release/obj.target/libyang/src/printer_yin.o
  CC(target) Release/obj.target/libyang/src/printer_yang.o
  CC(target) Release/obj.target/libyang/src/xpath.o
  CC(target) Release/obj.target/libyang/src/printer.o
  CC(target) Release/obj.target/libyang/src/tree_data.o
  CC(target) Release/obj.target/libyang/src/tree_schema.o
  CC(target) Release/obj.target/libyang/src/parser_yang.o
  CC(target) Release/obj.target/libyang/src/parser_yang_lex.o
  CC(target) Release/obj.target/libyang/src/parser_yang_bis.o
  CC(target) Release/obj.target/libyang/src/parser_json.o
  CC(target) Release/obj.target/libyang/src/parser_xml.o
  CC(target) Release/obj.target/libyang/src/parser_yin.o
  CC(target) Release/obj.target/libyang/src/parser.o
../src/parser.c: In function 'lyp_search_file':
../src/parser.c:287:29: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
                     asprintf(&match_name, "%s/%s", wd, file->d_name);
                             ^
../src/parser.c:295:25: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
                 asprintf(&match_name, "%s/%s", wd, file->d_name);
                         ^
../src/parser.c:313:21: warning: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Wunused-result]
             asprintf(&match_name, "%s/%s", wd, file->d_name);
                     ^
  CC(target) Release/obj.target/libyang/src/xml.o
  CC(target) Release/obj.target/libyang/src/validation.o
  CC(target) Release/obj.target/libyang/src/resolve.o
  CC(target) Release/obj.target/libyang/src/dict.o
  CC(target) Release/obj.target/libyang/src/log.o
  CC(target) Release/obj.target/libyang/src/context.o
  CC(target) Release/obj.target/libyang/src/common.o
  CXX(target) Release/obj.target/libyang/src/libyang_javascriptJAVASCRIPT_wrap.o
  SOLINK_MODULE(target) Release/obj.target/yang.node
  COPY Release/yang.node
make: Leaving directory `/tmp/node_modules/libyang/build'
/tmp
`-- libyang@1.0.11 

npm WARN enoent ENOENT: no such file or directory, open '/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.
```
Try building it with:
node-gyp configure                                                                             
node-gyp build

How did you install node-gyp?
In docker it is installed with:

```
npm install -g node-gyp
```

I did had some trouble with node-gyp in docker before.

At the moment I am working on some helper functions for casting libyang nodes in javascript. You can expect a patch in the following days.
