### ISSUE TITLE
crash in lyd_new_path

### ISSUE THREAD

**Issue by rastislavszabo** [CESNET/libyang#88]
```
Program received signal SIGSEGV, Segmentation fault.
0x76d50824 in resolve_partial_json_data_nodeid (nodeid=0x745004b8 "/sysrepo-raspberry-demo:temperature", llist_value=0x74500468 "28.123", start=0x74701490, options=1, parsed=0x75b13c6c)
    at /home/pi/libs/libyang/src/resolve.c:1659
1659        ctx = start->schema->module->ctx;
(gdb) bt
#0  0x76d50824 in resolve_partial_json_data_nodeid (nodeid=0x745004b8 "/sysrepo-raspberry-demo:temperature", llist_value=0x74500468 "28.123", start=0x74701490, options=1,
    parsed=0x75b13c6c) at /home/pi/libs/libyang/src/resolve.c:1659
#1  0x76dad754 in lyd_new_path (data_tree=0x74701490, ctx=0x32178, path=0x745004b8 "/sysrepo-raspberry-demo:temperature", value=0x74500468 "28.123", options=1)
    at /home/pi/libs/libyang/src/tree_data.c:737
```

YANG model: https://github.com/sysrepo/sysrepo-raspberry-pi/blob/master/yang/sysrepo-raspberry-demo.yang

**Comment by michalvasko** [comment]
Hi,
I didn't manage to simply reproduce it. Is the context somehow special (I used searchdir "."), what is the `data_tree` you are appending to (I did not append anywhere)?

Regards,
Michal

**Comment by rastislavszabo** [comment]
Hi,
it that case it also might be an issue in sysrepo. We will investigate further and update here.

**Comment by rastislavszabo** [comment]
It was probably some memory corruption issue in sysrepo, closing for now. Thanks.
