### ISSUE TITLE
lyd_parse_xml() segfault

### ISSUE THREAD

**Issue by gitter-runner** [CESNET/libyang#890]
Hi!

When I send the following XML via netopeer2 libyang segfaults:

```
<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:t3="urn:com:test3"
     message-id="1">
  <edit-config>
    <target>
      <running/>
    </target>
    <config>
      <advanced xmlns="urn:com:test">
        <double_indirection xmlns="urn:com:test3"
xmlns:t="urn:com:test">"/t:advanced/t3:double_indirection"</double_indirection>
      </advanced>
    </config>
  </edit-config>
</rpc>
```

And the error message is the following:

```
2019-10-02 08:35:48,032 DEBG 'netopeer2-server' stdout output:
[ERR]: Invalid value "/t:advanced/t3:double_indirection" in "double_indirection" element.
(/test:advanced/test3:double_indirection)

2019-10-02 08:38:02,585 DEBG 'netopeer2-server' stdout output:
=================================================================

2019-10-02 08:38:02,586 DEBG 'netopeer2-server' stdout output:
==11==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xf4a65ef7 at pc 0xf7a13315 bp 0xf03fe528 sp 0xf03fe0f8 WRITE of size 33 at 0xf4a65ef7 thread T2

2019-10-02 08:38:02,620 DEBG 'netopeer2-server' stdout output:
    #0 0xf7a13314 in __interceptor_strncpy (/usr/lib/i386-linux-gnu/libasan.so.4+0x97314)

2019-10-02 08:38:02,620 DEBG 'netopeer2-server' stdout output:
    #1 0xf7613a58 in transform_xml2json_subexp /opt/dev/libyang/src/common.c:552
    #2 0xf76140e8 in transform_xml2json /opt/dev/libyang/src/common.c:591

2019-10-02 08:38:02,621 DEBG 'netopeer2-server' stdout output:
    #3 0xf769a3bd in lyp_parse_value /opt/dev/libyang/src/parser.c:1621

2019-10-02 08:38:02,622 DEBG 'netopeer2-server' stdout output:
    #4 0xf7701180 in xml_get_value /opt/dev/libyang/src/parser_xml.c:95
    #5 0xf7705327 in xml_parse_data /opt/dev/libyang/src/parser_xml.c:456

2019-10-02 08:38:02,622 DEBG 'netopeer2-server' stdout output:
    #6 0xf7705f94 in xml_parse_data /opt/dev/libyang/src/parser_xml.c:510
    #7 0xf7707c16 in lyd_parse_xml /opt/dev/libyang/src/parser_xml.c:680
    #8 0x565adbd8 in op_import_anydata (/usr/local/bin/netopeer2-server+0x13bd8)
    #9 0x565ae65f in op_editconfig (/usr/local/bin/netopeer2-server+0x1465f)
    #10 0xf75cbe07 in nc_ps_poll (/usr/local/lib/libnetconf2.so.0.12+0x1ae07)

2019-10-02 08:38:02,622 DEBG 'netopeer2-server' stdout output:
    #11 0x565a3203 in worker_thread (/usr/local/bin/netopeer2-server+0x9203)
    #12 0xf79ab610  (/usr/lib/i386-linux-gnu/libasan.so.4+0x2f610)
    #13 0xf795e3bc in start_thread (/lib/i386-linux-gnu/libpthread.so.0+0x63bc)

2019-10-02 08:38:02,623 DEBG 'netopeer2-server' stdout output:
    #14 0xf6fd8e15 in clone (/lib/i386-linux-gnu/libc.so.6+0xf8e15)


2019-10-02 08:38:02,623 DEBG 'netopeer2-server' stdout output:
0xf4a65ef7 is located 0 bytes to the right of 39-byte region [0xf4a65ed0,0xf4a65ef7) allocated by thread T2 here:
    #0 0xf7a622e4 in __interceptor_realloc (/usr/lib/i386-linux-gnu/libasan.so.4+0xe62e4)
    #1 0xf761a7b8 in ly_realloc /opt/dev/libyang/src/common.c:1317
    #2 0xf76132e2 in transform_xml2json_subexp /opt/dev/libyang/src/common.c:515
    #3 0xf7613949 in transform_xml2json_subexp /opt/dev/libyang/src/common.c:551

2019-10-02 08:38:02,623 DEBG 'netopeer2-server' stdout output:
    #4 0xf76140e8 in transform_xml2json /opt/dev/libyang/src/common.c:591
    #5 0xf769a3bd in lyp_parse_value /opt/dev/libyang/src/parser.c:1621
    #6 0xf7701180 in xml_get_value /opt/dev/libyang/src/parser_xml.c:95
    #7 0xf7705327 in xml_parse_data /opt/dev/libyang/src/parser_xml.c:456
    #8 0xf7705f94 in xml_parse_data /opt/dev/libyang/src/parser_xml.c:510
    #9 0xf7707c16 in lyd_parse_xml /opt/dev/libyang/src/parser_xml.c:680

2019-10-02 08:38:02,624 DEBG 'netopeer2-server' stdout output:
    #10 0x565adbd8 in op_import_anydata (/usr/local/bin/netopeer2-server+0x13bd8)

Thread T2 created by T0 here:
    #0 0xf7a4a0d6 in __interceptor_pthread_create (/usr/lib/i386-linux-
gnu/libasan.so.4+0xce0d6)
    #1 0x565a0df2 in main (/usr/local/bin/netopeer2-server+0x6df2)
    #2 0xf6ef8e80 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18e80)


2019-10-02 08:38:02,624 DEBG 'netopeer2-server' stdout output:
SUMMARY: AddressSanitizer: heap-buffer-overflow (/usr/lib/i386-linux-
gnu/libasan.so.4+0x97314) in __interceptor_strncpy

2019-10-02 08:38:02,624 DEBG 'netopeer2-server' stdout output:
Shadow bytes around the buggy address:
  0x3e94cb80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e94cb90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e94cba0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e94cbb0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3e94cbc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x3e94cbd0: fa fa fa fa fa fa fa fa fa fa 00 00 00 00[07]fa
  0x3e94cbe0: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fa
  0x3e94cbf0: fa fa fd fd fd fd fd fa fa fa 00 00 00 00 02 fa
  0x3e94cc00: fa fa 00 00 00 00 00 fa fa fa 00 00 00 00 00 fa
  0x3e94cc10: fa fa 00 00 00 00 04 fa fa fa fd fd fd fd fd fa
  0x3e94cc20: fa fa 00 00 00 00 00 00 fa fa 00 00 00 00 04 fa Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==11==ABORTING
```

I used the same docker as I had used for my other issue, if you need any help with setting it up, just tell me.

Thanks!

**Comment by gitter-runner** [comment]
#817

**Comment by michalvasko** [comment]
Hi,
I am sorry, I really dislike `docker` because even if I managed to reproduce it, I would not be able to debug it. Also, the lines do not match with the current *libyang* so I cannot even go on that. Please, try at least updating *libyang* and then post the output, it may be enough, thanks.

Regards,
Michal

**Comment by fredgan** [comment]
@michalvasko Hi, Michal.  I know nothing about netopeer so I can't help for this problem. 
But for docker, when you start a Container, you can use following params to open debug function in docker.
```
--cap-add=SYS_PTRACE --security-opt seccomp=unconfined
```

Such as:
```
docker run --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -it -v $PWD:/data/libyang  --name="libyang-gdb" basic/ubuntu_18.04_gcc_7.4 bash
```

then, you can use the gdb.
